<html lang="en">
    
    <head>

<meta name="viewport" content="initial-scale=1.0">
<meta name="robots" content="noai, noimageai">



<link rel="shortcut icon" type="image/x-icon" href="/generators/favico.png" />
            <link href="https://fonts.googleapis.com/css?family=Source+Code+Pro:200,600|Major+Mono+Display" rel="stylesheet">
            
<?php
$sexytimes = array("Hurt/Comfort",
"Fluff",
"Fluff And Smut",
"Smut",
"Humor",
"Fluff And Humor",
"Oral Sex",
"Anal Sex",
"Domestic Fluff",
"Pregnancy Kink",
"Urethral Play",
"Prostate Massage",
"Prostate Milking",
"Sex Toys",
"Ear Cleaning",
"Back Scratching",
"Infantilism",
"Foot Fetish",
"Massage",
"Urination",
"Penis Polishing",
"Testicles Play",
"Nipple Play",
"Nipple Licking",
"Orgasm Delay/Denial",
"Missionary Position",
"Multiple Sex Positions",
"69 (Sex Position)",
"Spooning",
"Chinese Food",
"Sexual Fantasy",
"Chickens",
"Rabbits",
"Masturbation",
"Mutual Masturbation",
"Voyeurism",
"Riding",
"Swearing",
"Forced Orgasm",
"Dry Orgasm",
"Butt Plugs",
"Anal Play",
"Anal Beads",
"Dildos",
"Mating Press",
"Breeding",
"Farting",
"Demonic Possession",
"Demon Sex",
"Naughtiness",
"Naughty",
"Anal Fingering",
"Finger Sucking",
"Foreskin Play",
"Blow Jobs",
"Hand Jobs",
"Dirty Talk",
"Bad Dirty Talk",
"Dirty Jokes",
"Water Sex",
"Conspiracy",
"Conspiracy Theories",
"Romance",
"Established Relationship",
"BDSM",
"Strong Female Characters",
"Bullying",
"Girl Power",
"Gay Sex",
"Drugged Sex",
"Foot Massage",
"Backrubs",
"Ball Massage",
"Outdoor Sex",
"Gratuitous Smut",
"Crack",
"Pantless",
"Ejaculate",
"Multiple Orgasms",
"Ass Play",
"Scissors Sex Position",
"Eggs",
"Watersports",
"Ruined Orgasm",
"Sex Everywhere In The House",
"Obsessive-Compulsive Disorder",
"Obsessive-Compulsive",
"Obsessive Behavior",
"Househusband",
"Working Wife",
"Magic",
"Dark Magic",
"Sex Magic",
"Blood Magic",
"Elemental Magic",
"Thighs",
"Intercrural Sex",
"Comfort Food",
"Korean Food",
"Frugal Lifestyle",
"Simple Living",
"Twerking",
"Animal Traits",
"Animal Instincts",
"Animal Play",
"Consensual Non-Consent",
"Dubious Consent",
"Mildly Dubious Consent",
"Extremely Dubious Consent",
"Consensual Sex",
"Consensual Kink",
"Rape/Non-Con Elements",
"Mutual Non-Con",
"Docking",
"Dating",
"Edgeplay",
"Drunk Sex",
"Drunkenness",
"Drunken Kissing",
"Drunken Flirting",
"Drunk Blow Jobs",
"Drunk Dancing",
"Sweet",
"Sweet/Hot",
"Underwear",
"Underwear Kink",
"Not Wearing Underwear",
"Underwear Theft",
"Eating",
"Food",
"Food Kink",
"Food Sex",
"Food Porn",
"Snacks & Snack Food",
"Shopping",
"Grocery Shopping",
"Body Hair",
"Body Image",
"Drama & Romance",
"Awkward Romance",
"Romantic Fluff",
"Romantic Comedy",
"Table Sex",
"Fireworks",
"Cowgirl Position",
"Reverse Cowgirl",
"Anal Gaping",
"Perversion",
"Bridal Carrying",
"Robots",
"Harems",
"Multiple Selves",
"Multiple Partners",
"Pedophilia",
"Shotacon",
"Snakes",
"Chinese Mythology & Folklore",
"Enemas",
"Polyamory",
"Polygamy",
"Business",
"Businessmen",
"Time Travel",
"Loss Of Virginity",
"Virginity",
"Virginity Kink",
"Spanking",
"Genderswap",
"Genderbending",
"Gender Or Sex Swap",
"Lolicon",
"Violence",
"Graphic Description",
"Blood And Gore",
"Furry",
"Bugs & Insects",
"Sex With Sentient Animals",
"Tentacle Monsters",
"Tentacle Sex",
"Tentacle Rape",
"God Complex",
"War",
"Interspecies Sex",
"Rope Bondage",
"Bondage",
"Non-Consensual Bondage",
"Non-Sexual Bondage",
"Chair Bondage",
"Handcuffs",
"Collars",
"Latex",
"Rubber",
"Wax Play",
"Whipping",
"Flogging",
"Vibrators",
"Cock & Ball Torture",
"Blindfolds",
"Nipple Clamps",
"Nipple Piercings",
"Nipple Torture",
"Electrocution",
"Erotic Electrostimulation",
"Tickling",
"Non-Consensual Tickling",
"Human Furniture",
"Humiliation",
"Science Fiction",
"Science Fiction & Fantasy",
"Hacking",
"Alternate Universe",
"Merman",
"Mermaid",
"Birthday",
"Birthday Sex",
"Birthday Presents",
"Birthday Fluff",
"Birthday Cake",
"Wall Sex",
"Gangbang",
"Gang Rape",
"Group Sex",
"Groupies",
"Sounding",
"Orgy",
"Drug Use",
"Drugs",
"Non-Consensual Drug Use",
"Drug",
"Kidnapping",
"Prostitution",
"Forced Prostitution",
"Child Abuse",
"Sexual Slavery",
"Explicit Sexual Content",
"Sexual Abuse",
"Bad Touch",
"Touching",
"Human Trafficking",
"Threats Of Violence",
"Threats Of Rape/Non-Con",
"Threats",
"Armpit Kink",
"Scat",
"Domestic Bliss",
"Fleshlight",
"Victim Blaming",
"Sexual Grooming",
"Vaginal Sex",
"Penis In Vagina Sex",
"Vaginal",
"Sex Doll",
"Butt Slapping",
"Non-Consensual Spanking",
"Creampie",
"Porn",
"Porn With Plot",
"Plot What Plot/Porn Without Plot",
"Porn With Feelings",
"Porn Watching",
"Porn Video",
"Puppy Love",
"Beast Mode Sex",
"Molestation",
"Hardcore",
"Forced Masturbation",
"Feminization",
"Consensual Underage Sex",
"Grooming",
"Stubble",
"Mustaches",
"Strategy & Tactics",
"Archery",
"Monsters",
"Golems",
"Demons",
"Magic-Users",
"Swordfighting",
"Swords",
"Swords & Sorcery",
"Torture",
"Psychological Torture",
"Blood And Torture",
"Genital Torture",
"Slut Shaming",
"Kink Shaming",
"Cock Slut",
"Implied/Referenced Child Abuse",
"Parent/Child Incest",
"Child Neglect",
"Childbirth",
"Adopted Children",
"Child Abandonment",
"Intimacy",
"Non-Sexual Intimacy",
"Birds",
"Fantasy",
"Wolves",
"Bees",
"Wet Dream",
"Dream Sex",
"Nightmares",
"Dreams And Nightmares",
"Dysfunctional Family",
"Fluff And Crack",
"Hypnotism",
"Horror",
"Psychological Horror",
"Animalistic",
"Foot Jobs",
"Macro/Micro",
"Giants",
"Shrinking",
"Suit Sex",
"Suit Kink",
"Suit Porn",
"Suits",
"Sperm",
"Sperm Play",
"Cock Vore",
"Vore",
"Time Loop",
"Petrification",
"Immobility",
"Tight Pants",
"Lingerie",
"Bikinis",
"Crossdressing",
"Cuckolding",
"Breastfeeding",
"Breast Fucking",
"Breasts",
"Rough Oral Sex",
"Kissing",
"Boys Kissing",
"Rough Kissing",
"French Kissing",
"Forehead Kisses",
"Surprise Kissing",
"Underage Kissing",
"Gentle Kissing",
"Public Blow Jobs",
"Non-Consensual Blow Jobs",
"Implied/Referenced Blow Jobs",
"Alley Blow Jobs",
"Fondling",
"Vaginal Fingering",
"Fingerfucking",
"Hand & Finger Kink",
"Tongues",
"Dirty Thoughts",
"Resurrection",
"Gore",
"Death",
"Possession",
"Inanimate Objects",
"Inanimate Object Porn",
"POV Inanimate Object",
"Heroism",
"Sins",
"Mortal Sins",
"Succubi & Incubi",
"Orgasm Denial",
"Edging",
"Morbid",
"Macabre",
"Undead",
"Cuddling & Snuggling",
"Sleepy Cuddles",
"Morning Cuddles",
"Naked Cuddling",
"Post-Coital Cuddling",
"Mother-Son Relationship",
"Father-Son Relationship",
"Mother-Daughter Relationship",
"Father-Daughter Relationship",
"Mother Complex",
"Fatherhood",
"Motherhood",
"Two Fathers",
"Incest",
"Father/Son Incest",
"Incest Kink",
"Oedipal Issues",
"Penis Size",
"Barbed Penis",
"Penises",
"Penis Measuring",
"Large Cock",
"Cock Rings",
"Cock Warming",
"Cock Worship",
"Cock Tease",
"Cockblocking",
"Cock Slapping",
"Cock Piercing",
"Cock Bondage",
"Attempt At Humor",
"Some Humor",
"Sexual Humor",
"Inappropriate Humor",
"Bad Humor",
"Dry Humping",
"Tenderness",
"Tender Sex",
"Water",
"Fat Shaming",
"Toesex",
"Baldness",
"Weight Gain",
"Weight Issues",
"Corruption",
"Angel Corruption",
"Priest Kink",
"Priests",
"Priest Abuse",
"Monks",
"Blasphemy",
"Corpse Desecration",
"Police",
"Police Brutality",
"Glory Hole",
"Flowers",
"Semi-Public Sex",
"Public Sex",
"Public Display Of Affection",
"Public Humiliation",
"Public Nudity",
"Public Hand Jobs",
"Public Masturbation",
"In Public",
"Ritual Public Sex",
"Small Penis",
"Sexual Assault",
"Ear Twisting",
"Ear Pulling",
"Women In Power",
"Women In The Military",
"Mystery",
"Past Child Abuse",
"Childhood Friends",
"Children",
"Childhood",
"Childhood Trauma",
"Slave Trade",
"Amusement Parks",
"Sex Is Fun",
"Rape",
"Implied/Referenced Rape/Non-Con",
"Attempted Rape/Non-Con",
"Rape Recovery",
"Rape Aftermath",
"Rape Fantasy",
"Underage Rape/Non-Con",
"Mind Rape",
"Rape Roleplay",
"Animal Abuse",
"Talking Animals",
"Harm To Animals",
"Animal Ears",
"Animal Attack",
"Heterosexual Sex",
"Impregnation",
"Story Within A Story",
"Fairy Tale Elements",
"Fairy Tale Style",
"Dark Fairy Tale Elements",
"Fairy Tale Parody",
"Fairy Tale Logic",
"Fairy",
"Body Paint",
"Body Part Kinks",
"Fur Kink",
"Fruit",
"Vegetables",
"Reverse Rape",
"Buddhist Character",
"Buddhism",
"Goddess Of Mercy - Freeform",
"Statue",
"Video Game Mechanics",
"Husbands",
"Wives",
"Deus Ex Machina",
"Belly Kink",
"Belly Rubs",
"Nipples",
"Large Breasts",
"Comedy",
"Dark Comedy",
"Tragedy/Comedy",
"Thriller",
"Revenge",
"Burglary",
"Robbery",
"Grave Robbers",
"Emotional Hurt/Comfort",
"Angst And Hurt/Comfort",
"Comfort",
"Mild Hurt/Comfort",
"Hurt No Comfort",
"Comfort/Angst",
"Comfort Sex",
"Comfort Reading",
"Comfort No Hurt",
"Medicine",
"Medieval Medicine",
"Bush Medicine",
"Knifeplay",
"Puzzles",
"Nostalgia",
"Reminiscing",
"First Kiss",
"Neck Kissing",
"Non-Consensual Kissing",
"True Love's Kiss",
"Friendship",
"Friends To Lovers",
"Friendship/Love",
"Friends With Benefits",
"Best Friends",
"Male-Female Friendship",
"Male Friendship",
"Romantic Friendship",
"Enemies To Friends",
"Groping",
"Sleep Groping",
"Non-Consensual Groping",
"Pinching",
"Investigations",
"Hugs",
"Demon Deals",
"Deal With A Devil",
"Emotional Manipulation",
"Manipulation",
"Mind Manipulation",
"Manipulative Relationship",
"Quickies",
"Budding Love",
"Aunts & Uncles",
"Single Parents",
"Arranged Marriage",
"Escape",
"Beards (Facial Hair)",
"Beards",
"Threesome - M/M/M",
"Threesome",
"Exams",
"School",
"Work",
"Stress Relief",
"Underage Sex",
"Underage Masturbation",
"Pack Orgies",
"Crows",
"Magical Realism",
"Alternate Reality",
"Feelings Realization",
"Dreams Vs. Reality",
"Virtual Reality",
"Reality Bending",
"Realization",
"Realistic",
"Reality",
"Dolls",
"Puppets",
"Foster Care",
"Adoption",
"Adopted Sibling Relationship",
"Reincarnation",
"Rebirth",
"Spirits",
"Spirit World",
"Souls",
"Dead People",
"Injury",
"Major Character Injury",
"Blood And Injury",
"Injury Recovery",
"Serious Injuries",
"Orientalism",
"ASMR",
"Mukbang",
"Smuggling",
"Implied/Referenced Character Death",
"Past Character Death",
"Near Death Experiences",
"Character Death Fix",
"Gangs",
"Gangsters",
"Unconsciousness",
"Nature",
"Nature Versus Nurture",
"Unconscious Sex",
"Sleepy/Unconscious Sex",
"Poisoning",
"Poison",
"Food Poisoning",
"Trolling",
"Trolls",
"Masks",
"Disguise",
"Mind Control",
"Mind Games",
"Mindfuck",
"Mind Sex",
"Brainwashing",
"Christianity",
"Inaccurate Christianity",
"Religious Imagery & Symbolism",
"Religion Kink",
"Religion",
"Cats",
"POV Animal",
"Gross",
"Fast Food",
"Noodle Sex",
"Original Character(s)",
"Minor Original Character(s)",
"POV Original Character",
"Major Original Character(s)",
"Slash",
"Male Slash",
"Food Metaphors",
"POV Multiple",
"Multiple Pairings",
"Multiple Penetration",
"Sexual Confusion",
"Gender Confusion",
"Fish",
"Frogs",
"Fantasizing",
"Jealousy",
"Peeping",
"Gossip",
"Disability",
"Disabled Character",
"Physical Disability",
"Mushy",
"Masochism",
"Light Masochism",
"Dominant Masochism",
"Minor Injuries",
"Head Injury",
"Forced Marriage",
"Polyandry",
"Adultery",
"Blood And Violence",
"Domestic Violence",
"Aftermath Of Violence",
"Sexual Violence",
"Consensual Violence",
"Non-Consensual Violence",
"Gender Disguise",
"Public Transportation",
"Publicity",
"Marriage Proposal",
"Marriage",
"Fake Marriage",
"Marriage Of Convenience",
"Same-Sex Marriage",
"Loving Marriage",
"Marriage Contracts",
"Love",
"Falling In Love",
"Love Confessions",
"Idiots In Love",
"True Love",
"Boys In Love",
"Declarations Of Love",
"Gay Male Character",
"Male Homosexuality",
"Reunions",
"Reunion Sex",
"Family Reunions",
"Weddings",
"Wedding Fluff",
"Wedding Night",
"Wedding Planning",
"Wedding Rings",
"Post-Wedding",
"Shotgun Wedding",
"Mpreg",
"Implied Mpreg",
"Post Mpreg",
"Angst With A Happy Ending",
"Happy Ending",
"Ambiguous/Open Ending",
"Eventual Happy Ending",
"Hopeful Ending",
"Fluffy Ending",
"Alternate Ending",
"Bittersweet Ending",
"Sad With A Happy Ending",
"Restaurants",
"Pampering",
"Male Protagonist",
"Second Chances",
"Second Time",
"Eating Disorders",
"Fur",
"Post-Finale",
"Speeches",
"Nose Picking",
"Epilogue",
"Pre-Epilogue",
"Interspecies Relationship(s)",
"Interspecies",
"Insight",
"Deepthroating",
"End Of The World",
"On Hiatus",
"Hiatus",
"Post-Hiatus",
"Returning Home",
"Return",
"Hope",
"Hope Vs. Despair",
"Homosexuality",
"Bad Puns",
"Puns & Word Play",
"Aphrodisiacs",
"Boats And Ships",
"Boat Sex",
"Face-Fucking",
"Fucking",
"Fucked Up",
"Temporary Amnesia",
"Amnesia",
"Questioning",
"Questions",
"Interrogation",
"Interracial Relationship",
"Coitus Interruptus",
"Masturbation Interruptus",
"Cunnilingus",
"Exposition",
"Drunken Confessions",
"Drunken Shenanigans",
"Government Conspiracy",
"Overweight",
"Obsession",
"Supernatural Elements",
"Teasing",
"Strip Tease",
"Floor Sex",
"Dungeon",
"Portals",
"Dimension Travel",
"Tsunderes",
"Brothers",
"Brotherly Love",
"Brotherly Bonding",
"Brotherhood",
"Brotherly Affection",
"Brother Feels",
"Brotherly Angst",
"Big Brothers",
"Protective Older Brothers",
"Step-Brothers",
"Little Brothers",
"Night Terrors",
"Party",
"Dinner",
"Family Dinners",
"New Year's Eve",
"New Years",
"New Year's Kiss",
"New Year's Fluff",
"Chinese New Year",
"Belly Dancing",
"Dandruff",
"Sibling Incest",
"Pseudo-Incest",
"Implied/Referenced Incest",
"Brother/Brother Incest",
"Past Sexual Abuse",
"Brother/Sister Incest",
"Demon Summoning",
"Demon Hunters",
"Pranks And Practical Jokes",
"Bad Jokes",
"Jokes",
"Dick Jokes",
"Horse Jokes",
"Roleplay",
"Sexual Roleplay",
"Hero Complex",
"Brother Complex",
"Circle Jerk",
"Uncircumcised Penis",
"Futanari",
"Women's Underwear",
"Panties",
"Heterosexuality",
"Pregnancy",
"Teen Pregnancy",
"Civil War",
"Holding Hands",
"Travel",
"World Travel",
"Insults",
"Affectionate Insults",
"Scratching",
"Role Reversal",
"Murder",
"Attempted Murder",
"Murder Mystery",
"Murderers",
"Brutal Murder",
"Body Horror",
"Survival Horror",
"Mysticism",
"Mystical Creatures",
"Killing",
"Mercy Killing",
"Chains",
"Boys In Chains",
"Magic Cock",
"Prison",
"Prison Sex",
"Bears",
"Immigration & Emigration",
"Training Camp",
"Campfires",
"Camp",
"Dorms",
"Minimalism",
"High School",
"Boarding School",
"School Uniforms",
"Classroom Sex",
"Training",
"Military Training",
"Survival Training",
"Teacher-Student Relationship",
"Thicc",
"Money",
"Business Trip",
"Commercials",
"Goat Farm",
"Cleaning",
"House Cleaning",
"Clerics",
"Trust Issues",
"Trust",
"Loss Of Trust",
"Trust Kink",
"Suspicions",
"Kitchen Sex",
"Cooking",
"Cooking Lessons",
"Chefs",
"Footjob",
"Home Improvement",
"Shower Sex",
"Showers",
"Masturbation In Shower",
"Bribery",
"Butlers",
"Dirty Dancing",
"Magic Fingers",
"Thumb-Sucking",
"Couch Cuddles",
"Cuddlefucking",
"Stomach Ache",
"Excessive Drinking",
"Gardens & Gardening",
"Origami",
"Telepathy",
"Telepathic Bond",
"Soul Bond",
"Psychic Bond",
"Normal Life",
"Slavery",
"Slaves",
"Servants",
"Canes",
"Walking Canes",
"Small Towns",
"Cities",
"Constructed Reality",
"Self-Esteem Issues",
"Self-Indulgent",
"Self-Doubt",
"Self-Discovery",
"Self-Acceptance",
"Self-Sacrifice",
"Self-Reflection",
"Self-Cest",
"Self-Destruction",
"Self-Denial",
"Bombs",
"Bombing",
"Wake-Up Sex",
"Post-Awakening",
"Pre-Awakening",
"Caves",
"Sex In A Cave",
"Glittering Caves",
"Touch-Starved",
"Non-Consensual Touching",
"Touchy-Feely",
"Forehead Touching",
"Mythical Beings & Creatures",
"Creation",
"Creation Myth",
"Imagination",
"Novel",
"Graphic Novel",
"Inspired By Novel",
"Daydreaming",
"Modern Era",
"Memory Loss",
"Memories",
"Childhood Memories",
"Memory Alteration",
"Repressed Memories",
"Recovered Memories",
"Memory Related",
"Memory Magic",
"Groundhog Day",
"Baking",
"Dream Demon",
"Trapped",
"Piano Sex",
"Piano",
"Music",
"Inspired By Music",
"Musical References",
"Musical Instruments",
"Folk Music",
"Music Creation",
"Rough Sex",
"Sex",
"Phone Sex",
"Sex Work",
"Sex Talk",
"From Sex To Love",
"Sex Education",
"Sex Addiction",
"Sexy Times",
"Sexy",
"Foreplay",
"Double Penetration",
"Double Anal Penetration",
"Double Penetration In One Hole",
"Double Oral Penetration",
"Triple Penetration",
"Twins",
"Triplets",
"Soul Selling",
"Weirdness",
"Weird Plot Shit",
"Weird Biology",
"Weird Fluff",
"Stranger Sex",
"Strangers",
"Potatoes",
"Cheating",
"Humorous Ending",
"Religious Humor",
"Outer Space",
"Space Flight",
"Space Stations",
"Sex In Space",
"Exhibitionism",
"Mars",
"Martians",
"Planets",
"Dating Sim",
"Online Dating",
"Double Dating",
"Mangos",
"Pineapples",
"Apples",
"Oranges",
"Bananas",
"Pregnant Sex",
"Unplanned Pregnancy",
"Forced Pregnancy",
"Magical Pregnancy",
"Bread",
"Bread Sex",
"Bread Crumbs",
"Blue Balls",
"Blues",
"Blueberries",
"Testicle Play",
"Yaoi",
"Hentai",
"Medical Professionals",
"Alternate Professions",
"Accidental Stimulation",
"Essays",
"Fertility Issues",
"Facial Hair",
"Chest Hair",
"Pubic Hair",
"Long Hair",
"Hair Washing",
"Hair Brushing",
"Haircuts",
"Hair",
"Hair Kink",
"Artificial Insemination",
"Artistic Liberties",
"Fuckbuddies",
"Fucking Machines",
"Doctor/Patient",
"Teacher/Student Roleplay",
"Prostate Examinations",
"Underage Prostitution",
"Implied/Referenced Underage Prostitution",
"Pizza",
"Retrospective",
"Secrets",
"Mechanics",
"Blacksmithing",
"Worldbuilding",
"Saving The World",
"World Of Ruin",
"Goddesses",
"Body Worship",
"Worship",
"Bathing/Washing",
"Machines",
"Washing Machine",
"Chastity Device",
"Cock Cages",
"Confinement",
"Solitary Confinement",
"Midwife",
"Antennae",
"Postnatal",
"Children Of Characters",
"Secret Children",
"Newborn Children",
"Children's Stories",
"Parent-Child Relationship",
"Maternal Instinct",
"Napping",
"Diapers",
"Dragon - Freeform",
"Cheese",
"Explosions",
"Fire",
"Wine",
"Alcohol",
"Pumpkins",
"Implied/Referenced Cheating",
"Not Cheating",
"Uterus",
"Double Vaginal Penetration",
"Talking Vagina",
"Vacation",
"Spirit World Vacation",
"Mind Control Aftermath & Recovery",
"Mind Meld",
"Mindless Fluff",
"Military",
"Military Uniforms",
"Military Backstory",
"Military Background",
"Military Ranks",
"Military Academy",
"Gaming",
"Crash Landing",
"Postpartum Depression",
"Personal Favorite",
"Personal Growth",
"Astrology",
"Traditional Astrology",
"Rats",
"Rats & Mice",
"Cows",
"Tigers",
"Horses",
"Horseback Riding",
"Horsemen",
"Sheep",
"Sheep & Goats",
"Monkeys",
"Roosters",
"Chicken Soup",
"Dogs",
"Pigs",
"Were-Creatures",
"Rebellion",
"Rebels",
"Inspirational Speeches",
"Wigs",
"Costumes",
"Fetish",
"Fetish Clothing",
"Cop Fetish",
"Talking",
"Drinking & Talking",
"Talking Penis",
"Talking Trees",
"Field Trip",
"Flight Attendants",
"Step-Sibling Incest",
"Reboot",
"Butterflies",
"Sexually Transmitted Diseases",
"Teenagers",
"Horny Teenagers",
"Teenage Rebellion",
"Teenage Dorks",
"Teenage Drama",
"Kama Sutra",
"Brother-Sister Relationships",
"Sister Complex",
"Scents & Smells",
"Old Married Couple",
"Grumpy Old Men",
"Dialect",
"Sex Change",
"Intersex",
"Hermaphrodites",
"Adventure & Romance",
"Interspecies Romance",
"Action & Romance",
"Slow Romance",
"Teen Romance",
"Eventual Romance",
"Words",
"Power Of Words",
"Propositions",
"Filming",
"Films",
"Hotel Sex",
"Hotels",
"Love Hotels",
"Shopping Malls",
"Online Shopping",
"Grocery Store",
"Punishment",
"Corporal Punishment",
"Capital Punishment",
"Missionaries",
"Mating",
"Male Lactation",
"Male Bonding",
"POV Female Character",
"POV Male Character",
"Uterine Replicators",
"Artificial Intelligence",
"Artistic Sensibilities",
"Artistic License",
"Sakura (Cherry Blossoms)",
"Babies",
"Temple",
"Stockholm Syndrome",
"Stockings",
"Bagels",
"Sandwiches",
"Sandwich",
"Political Campaigns",
"Spring",
"Summer",
"Summer Vacation",
"Autumn",
"Winter",
"Possessive Sex",
"Tent Sex",
"Crazy",
"Insanity",
"Bipolar Disorder",
"Master/Servant",
"Master & Servant",
"Cannibalism",
"Independence",
"Alien Mythology/Religion",
"Fictional Religion & Theology",
"Intoxication",
"Freedom",
"Panic Attacks",
"Panic",
"Death Threats",
"Pre-Threesome",
"Foursome - M/M/M/M",
"Foursome",
"Fivesome - M/M/M/M/M",
"Fivesome",
"Sixsome",
"Muscles",
"Daddy Kink",
"Sugar Daddy",
"Princes & Princesses",
"Battle",
"Porn Battle",
"Epic Battles",
"Space Battles",
"Final Battle",
"Post-Battle",
"Battle Couple",
"Battlefield",
"Demonic Cultivation (Módào Zǔshī)",
"Shameless Smut",
"Shame",
"Shameless",
"Hair-Pulling",
"Hair Braiding",
"Making Out",
"Making Love",
"Making Up",
"Breaking Up & Making Up",
"Drama",
"Family Drama",
"Psychological Drama",
"Chair Sex",
"Chairs",
"Tablets",
"Seduction",
"Attempted Seduction",
"Sensuality",
"Sensual Play",
"Ridiculous",
"Married Sex",
"So Married",
"Infidelity",
"Past Infidelity",
"Emotional Infidelity",
"Consensual Infidelity",
"Sickfic",
"Daughters",
"Underage Drinking",
"Implied/Referenced Underage Sex",
"Underage Drug Use",
"Extremely Underage",
"Implied/Referenced Underage Drinking",
"Compare And Contrast",
"Companions",
"Blood Pacts",
"Kissing It Better",
"Technobabble",
"Technology",
"Alien Technology",
"Ancient Technology",
"Technological Kink",
"Reconciliation Sex",
"Reconciliation",
"Laughter",
"Laughter During Sex",
"Evil Laughter",
"Sex Toys Under Clothing",
"Improvised Sex Toys",
"Non-Penetrative Sex Toys",
"Swingers",
"Promiscuity",
"Threesome - F/M/M",
"Threesome - F/F/M",
"Foursome - F/F/M/M",
"Come Inflation",
"Inflation",
"Lesbian Sex",
"Useless Lesbians",
"Teleportation",
"First Time",
"21st Century",
"Sleeping Bag Sex",
"Fierce Corpse Wēn Níng | Wēn Qiónglín",
"Daddy Issues",
"Arson",
"Primitive Culture",
"Tribadism",
"Little Sisters",
"Milking",
"Milk",
"Milkshakes",
"Double Penetration In Two Holes",
"Foxes",
"Double Entendre",
"Seven Deadly Sins",
"Scum Villain References",
"Office Sex",
"Office",
"Travelogue",
"Interplanetary Travel",
"Harry Potter References",
"Illegal Activities",
"Prohibition",
"Youtube",
"Moaning",
"Years Later",
"Lucid Dreaming",
"Alternate Universe - Canon Divergence",
"Alternate Universe - Modern Setting",
"Alternate Universe - College/University",
"Alternate Universe - High School",
"Alternate Universe - Soulmates",
"Alternate Universe - Fantasy",
"Alternate Universe - Coffee Shops & Cafés",
"Alternate Universe - Everyone Lives/Nobody Dies",
"Alternate Universe - Historical",
"Alternate Universe - No Powers",
"Chores",
"Laundry",
"Christmas",
"Christmas Fluff",
"Christmas Tree",
"Christmas Decorations",
"Filthy",
"Erotica",
"Erotic Games",
"Brothels",
"Parenthood",
"Bad Parenting",
"Abusive Parents",
"Meeting The Parents",
"Sexual Dysfunction",
"Dysfunctional Relationships",
"Starvation",
"Some Plot",
"Slang",
"Spoons",
"Chopsticks",
"Egg Laying",
"Sound Effects",
"Non-Human Genitalia",
"Genital Piercing",
"Nosebleed",
"Early Mornings",
"Early In Canon",
"Early Days",
"Ears",
"Earrings",
"Bracelets",
"Necklaces",
"Necks",
"Peer Pressure",
"Drinking",
"Blood Drinking",
"Heavy Drinking",
"Binge Drinking",
"Drink Spiking",
"Soft Drinks",
"Tea",
"Chocolate",
"Coffee",
"Bakery",
"Baked Goods",
"The Sands Of Time",
"Islands",
"Furniture Shopping",
"Married Couple",
"Tricksters",
"Magic Tricks",
"Drug Abuse",
"References To Drugs",
"Implied/Referenced Drug Use",
"Drug Addiction",
"Past Drug Use",
"Implied/Referenced Drug Addiction",
"Drug Dealing",
"Drug-Induced Sex",
"Past Drug Addiction",
"Sins Of Youth",
"Fate",
"Fate & Destiny",
"Fate Worse Than Death",
"Jiāng Yànlí's Pork Rib And Lotus Root Soup",
"Lotus Pier (Módào Zǔshī)",
"Clouds",
"Cloud Watching",
"Cloud Recesses (Módào Zǔshī)",
"Carp Tower | Koi Tower (Módào Zǔshī)",
"Burial Mounds (Módào Zǔshī)",
"Golden Core Transfer (Módào Zǔshī)",
"Night Hunts (Módào Zǔshī)",
"Gūsū Lán Sect Rules (Módào Zǔshī)",
"Gūsū Lán Forehead Ribbon (Módào Zǔshī)",
"Gūsū Lán Silencing Spell (Módào Zǔshī)",
"Qíshān Wēn Indoctrination (Módào Zǔshī)",
"Inappropriate Use Of Gūsū Lán Silencing Spell (Módào Zǔshī)",
"Inappropriate Use Of Bìchén (Módào Zǔshī)",
"Incense Burner (Módào Zǔshī)",
"Alternate Universe - Gender Changes",
"Illegitimacy",
"Grandparents & Grandchildren",
"Grandmothers",
"Grandchildren",
"Good",
"I'm Bad At Tagging",
"I'm Bad At Summaries",
"Bad Flirting",
"Bad Decisions",
"Bad Ending",
"I'm Bad At Titles",
"Feel-Good",
"Goodbyes",
"Past Rape/Non-Con",
"Violation",
"Fuck Or Die",
"Coming In Pants",
"Pants",
"Shirtless",
"Lactation Kink",
"Lactation",
"Enemies To Friends To Lovers",
"Enemies To Lovers",
"Enemies",
"Friends To Enemies",
"Female Friendship",
"Developing Friendships",
"Tragic Romance",
"Angst And Romance",
"Post-Coital",
"Boku No Hero Academia | My Hero Academia References",
"Minor Jiāng Chéng | Jiāng Wǎnyín/Wēn Qíng",
"Cinnamon Roll Wēn Níng | Wēn Qiónglín",
"Mentioned Wēn Cháo (Módào Zǔshī)",
"Ultimate Sacrifice",
"BJYX | Wang Yi Bo/Xiao Zhan | Sean Is Real",
"Final Fantasy Vii Spoilers",
"Breakfast",
"Breakfast In Bed",
"Bed & Breakfast",
"Mental Breakdown",
"Breaking The Fourth Wall",
"Breaking And Entering",
"Curse Breaking",
"Lunch",
"Shingeki No Kyojin | Attack On Titan References",
"Clairvoyance",
"Fights",
"Fist Fights",
"Crime Fighting",
"Fight Sex",
"Tickle Fights",
"Play Fighting",
"Food Fight",
"Fighting Kink",
"Pillow Fights",
"Freedom Fighters",
"Catboys & Catgirls",
"Necrophilia",
"Necromancy",
"Heartbreak",
"Heartache",
"Heartbreaking",
"Heart-To-Heart",
"Heartbeats",
"Heart Attacks",
"Heartbeat Kink",
"Dark Souls (Video Game) References",
"Giant Robots",
"Giant Spiders",
"Human Experimentation",
"Cat/Human Hybrids",
"Human",
"Robot/Human Relationships",
"Human/Vampire Relationship",
"Human/Monster Romance",
"Natural Disasters",
"Disasters",
"Light BDSM",
"Bad BDSM Etiquette",
"BDSM Scene",
"Heavy BDSM",
"Platonic BDSM",
"Science",
"Science Experiments",
"Dubious Science",
"Mad Science",
"Mad Scientists",
"Fake Science",
"Magic And Science",
"Magic Revealed",
"Magical Tattoos",
"Magical Artifacts",
"Magical Accidents",
"Tattoos",
"Sleeping Together",
"Sleep",
"Literal Sleeping Together",
"Sleep Deprivation",
"Sleepovers",
"Sleepiness",
"Sleep Sex",
"Watching Someone Sleep",
"Sleeping Beauty Elements",
"Sleeptalking",
"Hiccups",
"Ownership",
"Home",
"Homelessness",
"Homecoming",
"Leaving Home",
"Coffee Shops",
"Bakery And Coffee Shop",
"Shoplifting",
"Show Business",
"Feudalism",
"Multiple Universes Colliding",
"Multiple Endings",
"Multiple Personalities",
"Multiple Crossovers",
"Multi-Era",
"Gambling",
"Post-Game(s)",
"Dialogue Heavy",
"Heavy Petting",
"Heavy Angst",
"Long",
"Long-Distance Relationship",
"Long-Term Relationship(s)",
"Long Shot",
"Long Lost/Secret Relatives",
"Long-Distance Friendship",
"Short",
"Short One Shot",
"Short & Sweet",
"Random & Short",
"Shorts",
"Shorts (Clothing)",
"Panty Kink",
"Lace Panties",
"Red Pants",
"Pink Panties",
"Social Commentary",
"Commentary",
"Inner Dialogue",
"Undercover",
"Undercover Missions",
"Woman On Top",
"Moving On",
"Older Man/Younger Woman",
"Older Man/Younger Man",
"Older Woman/Younger Man",
"Older Characters",
"Young Love",
"Scent Kink",
"Voice Kink",
"Wing Kink",
"Blood Kink",
"Size Kink",
"Bank Robbery",
"Stealth Crossover",
"Soup",
"Soup Kitchens",
"Poverty",
"Poor Life Choices",
"Bisexuality",
"Bisexual Male Character",
"Cybernetics",
"Cybercrimes",
"Cyberpunk",
"Magical Healing Cock",
"Unrequited Love",
"Dorks In Love",
"Love/Hate",
"First Love",
"Love At First Sight",
"Love Triangles",
"Forbidden Love",
"Lovely",
"Big Gay Love Story",
"We Just Love Each Other",
"I Love You",
"You Have Been Warned",
"Their Love Is So",
"Love Potion/Spell",
"Love Letters",
"Love Bites",
"Teeth",
"Blow Jobs With Teeth",
"Fanboys - Freeform",
"Crossdressing Kink",
"Star-Crossed",
"Cross-generation Relationship",
"Forced Crossdressing",
"Crossing Timelines",
"Cross-Generational Friendship",
"Cross-Cultural",
"Crossing Parallels",
"Crossover",
"Crossovers & Fandom Fusions",
"Crack Crossover",
"Comics/Movie Crossover",
"Everybody Lives",
"Past Lives",
"Slice Of Life",
"Married Life",
"Alternate Universe - Normal Life",
"Real Life",
"Platonic Life Partners",
"Double Life",
"Life Partners",
"Matter Of Life And Death",
"Life Debt",
"Life-Affirming Sex",
"House Party",
"Beach House",
"House Hunting",
"Office Blow Jobs",
"Office Supplies",
"Office Party",
"Contracts",
"IN SPACE!",
"Space Opera",
"Space Wives",
"Language of Flowers",
"Flower Crowns",
"Immaturity",
"Immortality",
"Immortals",
"Immorality",
"Frottage",
"Dancing",
"Slow Dancing",
"Pole Dancing",
"Dancing and Singing",
"Dancing Lessons",
"Dancing in the Rain",
"Superpowers",
"Superpower Sex",
"Marvel Universe",
"DC Comics References",
"X-Men References",
"Yílíng Lǎozǔ Wèi Yīng | Wèi Wúxiàn",
"Oblivious Wèi Yīng | Wèi Wúxiàn",
"Soft Lán Zhàn | Lán Wàngjī/Wèi Yīng | Wèi Wúxiàn",
"POV Wèi Yīng | Wèi Wúxiàn",
"Female Wèi Yīng | Wèi Wúxiàn",
"Protective Wèi Yīng | Wèi Wúxiàn",
"Top Wèi Yīng | Wèi Wúxiàn",
"Minor Lán Zhàn | Lán Wàngjī/Wèi Yīng | Wèi Wúxiàn",
"Pining Wèi Yīng | Wèi Wúxiàn",
"Bottom Lán Zhàn | Lán Wàngjī/Top Wèi Yīng | Wèi Wúxiàn",
"BAMF Wèi Yīng | Wèi Wúxiàn",
"Older Wèi Yīng | Wèi Wúxiàn",
"Sad Wèi Yīng | Wèi Wúxiàn",
"Female Lán Zhàn | Lán Wàngjī/Female Wèi Yīng | Wèi Wúxiàn",
"Bottom Lán Zhàn | Lán Wàngjī",
"POV Lán Zhàn | Lán Wàngjī",
"Lán Zhàn | Lán Wàngjī Has Feelings",
"Dark Lán Zhàn | Lán Wàngjī",
"Top Lán Zhàn | Lán Wàngjī",
"Pining Lán Zhàn | Lán Wàngjī",
"Jealous Lán Zhàn | Lán Wàngjī",
"Protective Lán Zhàn | Lán Wàngjī",
"Female Lán Zhàn | Lán Wàngjī",
"Possessive Lán Zhàn | Lán Wàngjī",
"Tentacle Dick",
"Dick Pics",
"Verbal Humiliation",
"Situational Humiliation",
"Shamanism",
"Walk Of Shame",
"Paganism",
"Pagan Gods",
"Pagan Festivals",
"Demigods",
"Deities",
"Oh My God",
"Oh God Yes",
"Elder God",
"Sun God",
"Sea God",
"Standardized Tests",
"Evil",
"Evil Plans",
"Good and Evil",
"Good versus Evil",
"Good Writing",
"Awesome",
"Noogies",
"No Plot/Plotless",
"Organ Transplantation",
"Organs",
"Simultaneous Orgasm",
"Orgasm Delay",
"Orgasm",
"Organized Crime",
"Orgasm Control",
"Tree Climbing",
"Flying",
"Flying Sex",
"Swimming",
"Swimming Pools",
"Swimming Boys",
"Walking In On Someone",
"Being Walked In On",
"Walks On The Beach",
"Walk Into A Bar",
"Walking",
"Walks In The Woods",
"Walks In The Park",
"Walkers",
"On the Run",
"Fashion & Couture",
"Old-Fashioned",
"Shirt Porn",
"Shoes",
"Shoe Kink",
"Socks",
"Belts",
"Magic Belt",
"Tie Kink",
"Mating Bites",
"Claiming Bites",
"Vampire Bites",
"Bitchslapping",
"Cryptozoology",
"Cryptography",
"Girl Saves Boy",
"Dubious Morality",
"Moral Ambiguity",
"Morally Ambiguous Character",
"Moral Dilemmas",
"Morality",
"Moral Lessons",
"Moral Bankruptcy",
"Just Add Kittens",
"Puppy Play",
"Puppeteer",
"Anal Fisting",
"Anal Probing",
"Anal",
"Anal Plug",
"Character Analysis",
"Analysis",
"Ballads",
"Ballet",
"Ben Wa Balls",
"Marshmallows",
"Teaching",
"Tea Parties",
"Chinese Character",
"A Chinese Ghost Story",
"Fishing",
"Fish out of Water",
"Fishnets",
"Fish Puns",
"Fish & Chips",
"Gay Chicken",
"Fire Powers",
"Fire Magic",
"Holy Water",
"Watercolors",
"Water Guns",
"Water Balloon Fights",
"Water Spirit",
"Waterboarding",
"Hot Chocolate",
"Chocobos",
"Sex and Chocolate",
"Chocolate Syrup",
"Chocolate Sauce",
"Altar Sex",
"Altars",
"Heaven",
"Heaven & Hell",
"Heaven vs Hell",
"Age Swap",
"Species Swap",
"Partner Swapping",
"Personality Swap",
"Identity Swap",
"Power Swap",
"Bodyswap",
"Body Modification",
"Body Dysphoria",
"Non-Consensual Body Modification",
"Sharing Body Heat",
"Sharing a Body",
"Bodyguard",
"Rough Body Play",
"Body Shots",
"Out of Body Experiences",
"Ice Skating",
"Ice Cream",
"Ice Play",
"Ice",
"Snow and Ice",
"Yaoi on Ice",
"Ice Cream Parlors",
"Ice Powers",
"Snow",
"Snowball Fight",
"Snowballing",
"Snow Day",
"Snow Angels",
"Hunters & Hunting",
"Ghost Hunters",
"Monster Hunters",
"Treasure Hunting",
"Not Really Character Death",
"Inspired by Real Events",
"Reality TV",
"Real Men Wear Tights",
"RPF",
"In-Universe RPF",
"Comedy RPF",
"Assassins & Hitmen",
"Attempted Sexual Assault",
"Implied/Referenced Sexual Assault",
"Assault",
"Assassination",
"Ass to Mouth",
"Past Sexual Assault",
"Assassination Plot(s)",
"Ass-Kicking",
"Demons Are Assholes",
"Police Procedural",
"Police Uniforms",
"Private Investigators",
"Paranormal Investigators",
"Dixing Powers (Guardian)",
"Dixing (Guardian)",
"Vanilla",
"Vanilla Kink",
"Vendettas",
"Video & Computer Games",
"Computers",
"Computer Programming",
"Computer Viruses",
"Misuse of Special Techniques",
"Chief Cultivator Lán Zhàn | Lán Wàngjī",
"Cultivation Sect Politics (Módào Zǔshī)",
"Cultivation Discussion Conferences (Módào Zǔshī)",
"Chestnuts Roasting On An Open Fire",
"Imprinting",
"Strawberries",
"Pets",
"Piglet",
"Veterans",
"Veterinary Clinic",
"Veterinary Medicine",
"Pet Names",
"Pet Store",
"Pet Sitting",
"Master/Pet",
"Painkillers",
"Pain",
"Painting",
"Painful Sex",
"Chronic Pain",
"Paintball",
"Back Pain",
"Paint Kink",
"Motorcycles",
"Beaches",
"Day At The Beach",
"Beach Sex",
"Beach Holidays",
"Beach Volleyball",
"Beach City",
"Nude Beach",
"Beer",
"Mini",
"Tampons",
"Menstruation",
"Menstrual Sex",
"Menstruation Kink",
"Hot",
"Hot Sex",
"Hot Springs & Onsen",
"Hot Weather",
"Hot Tub",
"Hot Tub Sex",
"Hot Space Era",
"Swim Team",
"Swim Club",
"Underwater",
"Underwater Sex",
"Underwater Blow Jobs",
"Big Fat Quiz of Everything",
"Gills",
"Gillplay",
"Locker Room",
"Cardiopulmonary Resuscitation",
"Skater Victor Nikiforov",
"Skater Katsuki Yuuri",
"Nick Fury is Not Amused",
"Nick Fury Knows All",
"Steve Rogers and the 21st Century",
"SOLDIER Cloud Strife",
"Minor Tifa Lockhart/Cloud Strife",
"Minor Aerith Gainsborough/Cloud Strife",
"Aerith Gainsborough Lives",
"Cid Highwind Swears A Lot",
"Sassy Peter Quill",
"I Am Groot (Marvel)",
"BAMF Bakugou Katsuki",
"BAMF Midoriya Issue",
"BAMF Sephiroth (Compilation of FFVII)",
"Rocket Launchers",
"Back to the Future References",
"Inspired by Back to the Future",
"Marvel References",
"Yuri!!! on Ice References",
"Clark Kent is Superman",
"Batman References",
"Bruce Wayne is Batman",
"Inspired by Wonder Woman (2017)",
"Inspired by Yuri!!! on Ice",
"X-Men Inspired",
"X-Men: Days of Future Past References",
"X-Men: First Class References",
"X-Men: Dark Phoenix (Movie) Spoilers",
"X-Men: Days of Future Past (2014)",
"X-Men: Days of Future Past Spoilers",
"Charles Xavier in a Wheelchair",
"Powerful Charles Xavier",
"Ororo Munroe is a Good Friend",
"Beast Hank McCoy",
"Awesome Hank McCoy",
"Good Friend Rogue (X-Men)",
"Scott is a Good Friend",
"Phoenixes",
"Dragon Riders",
"Quests",
"Pre-Quest",
"Post-Quest",
"Side Quests",
"Jean Grey Lives",
"Hero's Quest References",
"Erik Lehnsherr is not a Happy Bunny",
"Villains",
"Heroes to Villains",
"Villains to Heroes",
"Possessive Shigaraki Tomura | Shimura Tenko",
"Dabi is Todoroki Touya",
"Dabi and Todoroki Shouto Are Siblings",
"Possessive Dabi (My Hero Academia)",
"Dabi is a Little Shit (My Hero Academia)",
"Nomu - Freeform",
"Loki (Marvel) Does What He Wants",
"Loki (Marvel) Has Issues",
"One of My Favorites",
"One-Sided Attraction",
"One Shot",
"One Shot Collection",
"One Night Stands",
"One-Sided Relationship",
"One True Pairing",
"One Big Happy Family",
"Two Shot",
"Two Minds One Body",
"Threesome - F/F/F",
"Threesome - M/M/Other",
"Foursome - F/M/M/M",
"Fourth Wall",
"Foursome - F/F/F/M",
"Foursome - F/F/F/F",
"Four Horsemen",
"Five Stages of Grief",
"Five Years Later",
"Fivesome - F/M/M/M/M",
"Seven Heavenly Virtues",
"Eight is Fate",
"The Nine Realms",
"Ten Years Later",
"Bottom Ten",
"Fifteen Minute Fic",
"Inspired by The Sixth Sense",
"Twenty Years Later",
"Three Years Later",
"Teen Years",
"Years of the Trees",
"One Punch Man References",
"Oblivious Saitama",
"Hero Saitama",
"Hero Genos",
"Hero Worship",
"Anti-Hero",
"Hero Association",
"Dragon Ball Z References",
"Babysitter Kurogiri (My Hero Academia)",
"Minor L/Yagami Light",
"Gay Yagami Light",
"Yagami Light is Kira",
"Death Note References",
"Inspired by Death Note",
"Death Note Spoilers",
"Light Angst",
"Light Bondage",
"Light Dom/sub",
"Light-Hearted",
"Light Sadism",
"Dialogue Light",
"Light Petting",
"Dark",
"Dark Past",
"Dark Character",
"Dark Fantasy",
"Pool Table Sex",
"Pundit Round Table",
"War Table Sex",
"Back Seat",
"Sharing a Bed",
"Bedroom Sex",
"Bed-Wetting",
"Bed Sex",
"Bedrooms",
"Beds",
"Breaking the Bed",
"Star Trek References",
"Jean-Luc Picard Is So Done",
"Klingon",
"Enterprise",
"Starship Enterprise (Star Trek)",
"Anxiety Attacks",
"Ambushes and Sneak Attacks",
"Titan Eren Yeager",
"Titan Shifter Eren Yeager",
"Titan War",
"Star Wars References",
"References to Star Wars: The Clone Wars (2008)",
"References to the Jedi Council (Star Wars)",
"Darth Vader Lives",
"BAMF Darth Vader",
"Darth Vader Has Issues",
"Death Star (Star Wars)",
"Character Death",
"Minor Character Death",
"Canonical Character Death",
"Temporary Character Death",
"Original Character Death(s)",
"Child Death",
"Animal Death",
"Near Death",
"Possible Character Death",
"Muggle Life",
"Somebody Lives/Not Everyone Dies",
"Severus Snape Lives",
"LiveJournal",
"Dreamwidth",
"Mentioned Stormtroopers (Star Wars)",
"Stormtrooper Culture (Star Wars)",
"Jedi Luke Skywalker",
"Luke Skywalker Lives",
"Luke Skywalker Is Not an Asshole",
"Leia Organa Deserves Better",
"Clones",
"Clone Sex",
"Han Solo Lives",
"Millenium Falcon (Star Wars)",
"Quidditch",
"Jurassic Park References",
"Alternate Universe - Jurassic Park Fusion",
"Quaffle",
"Dinosaurs",
"Alternate Universe - Dinosaurs",
"Needs More Dinosaurs!",
"Tyrannosaurus Rex - Freeform",
"Evil Voldemort (Harry Potter)",
"Good Albus Dumbledore",
"Albus Dumbledore Lives",
"Compsognathus",
"Brachiosaurus",
"Triceratops",
"Golden Snitches (Harry Potter)",
"Gryffindor/Slytherin Inter-House Relationships",
"Slytherin",
"Gryffindor",
"Velociraptors",
"Raptors",
"Team Parents Sawamura Daichi/Sugawara Koushi",
"Team Dad Sawamura Daichi",
"Team Mom Sugawara Koushi",
"Established Azumane Asahi/Nishinoya Yuu",
"Insecure Azumane Asahi",
"Nervous Azumane Asahi",
"Thunder and Lightning",
"Awkward Kageyama Tobio",
"Minor Hinata Shouyou/Kageyama Tobio",
"Hinata Shouyou & Kageyama Tobio Friendship",
"Hinata Shouyou is Sunshine",
"Tsukishima Kei & Yamaguchi Tadashi Friendship",
"Minor Tsukishima Kei/Yamaguchi Tadashi",
"Hinata Shouyou & Tsukishima Kei Friendship",
"Possessive Tsukishima Kei",
"Jealous Tsukishima Kei",
"Hinata Shouyou & Yamaguchi Tadashi Friendship",
"Giraffes",
"Lions",
"Lion King (1994) References",
"Elephants",
"Rhinoceros",
"Warthog",
"Wild Hunt",
"Wild Boar",
"Chu Wanning Has Self-Esteem Issues",
"Minor Chu Wanning/Mo Ran | Mo Weiyu",
"Xue Yang | Xue Chengmei is a Brat",
"Xue Yang | Xue Chengmei Deserves Better",
"Jin Ling | Jin Rulan Loves Jiang Cheng | Jiang Wanyin",
"Cute Mark Tuan",
"Shy Im Jaebum | JB",
"Alpha Jackson Wang",
"Cute Park Jinyoung (GOT7)",
"Cute Choi Youngjae",
"Soft Kunpimook Bhuwakul | BamBam",
"Soft Kim Yugyeom",
"Cute Kim Minseok | Xiumin",
"Prince Kim Junmyeon | Suho",
"Cute Zhang Yi Xing | Lay",
"Singer Byun Baekhyun",
"Sassy Kim Jongdae | Chen",
"Sweet Park Chanyeol",
"Byun Baekhyun & Do Kyungsoo | D.O Friendship",
"Shy Do Kyungsoo | D.O",
"Cute Kim Jongin | Kai",
"Cute Oh Sehun",
"Whipped Son Hyunwoo | Shownu",
"Dom Lee Minhyuk (Monsta X)",
"Rich Yoo Kihyun",
"Model Chae Hyungwon",
"Artist Lee Jooheon (Monsta X)",
"Cute Im Changkyun | I.M",
"Pop Culture",
"Popcorn",
"K-pop References",
"Mentioned Other K-pop Artist(s)",
"Hip Hop",
"Non-Graphic Rape/Non-Con",
"Date Rape Drug/Roofies",
"Rock Stars",
"Rock and Roll",
"Sex Drugs and Rock and Roll",
"Punk Rock",
"Glam Rock",
"Prehistoric",
"Alternate Universe - Prehistoric",
"Musicals",
"Musicians",
"Classical Music",
"80's Music",
"90's Music",
"Kinky Lee Jinki | Onew",
"Top Kim Kibum | Key",
"Soft Choi Minho",
"Dancer Lee Taemin",
"Bad Boy Choi Seungcheol | S.Coups",
"Angel Yoon Jeonghan",
"Soft Hong Jisoo | Joshua",
"Shy Wen Jun Hui | Jun",
"Kwon Soonyoung | Hoshi is Whipped",
"Confused Jeon Wonwoo",
"Lee Jihoon | Woozi is Whipped",
"Beta Lee Seokmin | DK",
"Model Kim Mingyu",
"Dancer Xu Ming Hao | The8",
"Sassy Boo Seungkwan",
"Shy Chwe Hansol | Vernon",
"Baby Lee Chan | Dino",
"Top Chef",
"Gordon Ramsey - Freeform",
"Bang Chan is a Good Friend",
"Flirty Lee Minho | Lee Know",
"Bad Boy Seo Changbin",
"Sweet Hwang Hyunjin",
"Cute Han Jisung | Han",
"Rich Lee Felix (Stray Kids)",
"Kim Seungmin is Whipped",
"Cute Yang Jeongin | I.N",
"Top Moon Taeil",
"Kim Dongyoung | Doyoung is Whipped",
"Top Jung Yoonoh | Jaehyun",
"Protective Lee Taeyong",
"Artist Chittaphon Leechaiyapornkul | Ten",
"Marking",
"Black Markets",
"Top Mark",
"Markers",
"Copic Markers",
"Come Marking",
"Scent Marking",
"Awkward Mark Lee (NCT)",
"Soft Nakamoto Yuta",
"Dancer Dong Si Cheng | WinWin",
"Shy Lee Donghyuck | Haechan",
"Oblivious Huang Ren Jun",
"Sweet Lee Jeno",
"Confident Na Jaemin",
"Stressed Zhong Chen Le",
"Awkward Park Jisung (NCT)",
"Rich Suh Youngho | Johnny",
"Top Kim Jungwoo (NCT)",
"Wong Yuk Hei | Lucas is Whipped",
"Sweet Qian Kun",
"Alpha Xiao De Jun | Xiao Jun",
"Rich Wong Kun Hang | Hendery",
"Top Liu Yang Yang",
"Bottom Osaki Shotaro",
"Dancer Jung Hoseok | J-Hope",
"Filet Mignon",
"Leather Jackets",
"Dean Winchester's Jacket",
"Protective Dean Winchester",
"Dean Winchester Needs a Hug",
"Dean Winchester is Bad at Feelings",
"Dean Winchester Whump",
"Face-Sitting",
"Face Slapping",
"Face Punching",
"Face Mask",
"Beanie - Freeform",
"Dark Glasses",
"Glasses",
"Looking Glass",
"Sunglasses",
"Crowley's Sunglasses (Good Omens)",
"Baristas",
"Sanitary Napkins",
"Lanyard",
"Guardian Forces | GFs (Final Fantasy VIII)",
"Guardian Angels",
"Quezacotl",
"Shiva - Freeform",
"Ifrit - Freeform",
"Bahamut - Freeform",
"Materia (Compilation of FFVII)",
"Fisherman's Horizon",
"Balamb Garden (Final Fantasy VIII)",
"Zerg - Freeform",
"Protoss",
"Zergling",
"Hydralisk",
"Ultralisk",
"Drone Season 2014",
"Creepy",
"Creepy Fluff",
"Creep",
"Overlord - Freeform",
"Overmind - Freeform",
"Cerebrate",
"Brooding",
"Brood",
"Leadership",
"Swarm",
"Zerg Rush",
"Mutalisk",
"Larva - Freeform",
"Metamorphosis",
"Pupae",
"Hatchery",
"Creep Colony",
"Colonization",
"Spore Colony",
"Sunken Colony",
"Evolution",
"Evolution Chamber",
"Peanut Butter",
"Gas Extractor",
"Vespene Geyser",
"Den - Freeform",
"Lair",
"Hive Mind",
"Hive",
"Nydus Canal",
"Kings & Queens",
"Drag Queens",
"Nesting",
"Devil's Nest",
"Queen’s Nest",
"Broodling",
"Spawning Pool",
"Pool Sex",
"Pool",
"Pool & Billiards",
"Parasites",
"Ensnare",
"Symbiosis",
"Psionics",
"Psionic Bondage",
"Psionic Sex",
"Spire - Freeform",
"Guardian-Ward Relationship",
"Guardian - Freeform",
"Pandora - Freeform",
"Na'vi",
"Direhorse | Pa'li (Avatar)",
"Mountain Ash",
"Banshees",
"Mountain Banshee",
"Great Hiatus",
"Great Old Ones",
"Great Leonopteryx",
"Viperwolves",
"Hammerhead Titanotheres",
"Thanator/Palulukan (Avatar)",
"Ur-Quan",
"Kohr-ah - Freeform",
"Arilou - Freeform",
"Syreen",
"Mycon",
"Earthling",
"Chmmr",
"Zentraedi",
"Bioroids",
"Invid",
"Protoculture",
"Human Sacrifice",
"Alien/Human Relationships",
"Orcs",
"Orchestra",
"Orc Culture",
"Orc Attack",
"Free Orcs",
"PEASANT",
"Town Hall",
"Lumber Mill",
"Barracks",
"Farms",
"Blacksmith - Freeform",
"Knights - Freeform",
"Death Knight",
"Elf/Human Relationship(s)",
"Elven Archer",
"Footman",
"Peon - Freeform",
"Grunt - Freeform",
"Axethrower",
"Ogres",
"Goblins",
"Zeppelin - Freeform",
"Gnomes",
"Fear of Flying",
"Catapult",
"Ballista",
"Fortress",
"Nexus - Freeform",
"Pylon",
"Assimilator",
"Golden Core Reveal (Módào Zǔshī)",
"CORE",
"Forgery",
"Forge - Freeform",
"Robotics",
"Facility",
"Stargate",
"Fleet Beacon",
"Gateway - Freeform",
"Dimension Cannon",
"Photon - Freeform",
"Electron - Freeform",
"Neutron - Freeform",
"Photon Cannon",
"SHIELD",
"Shield Battery",
"Probe - Freeform",
"Zealot - Freeform",
"Reaver - Freeform",
"Dragoon",
"Templars",
"High Templar",
"Dark Templar - Freeform",
"Observer",
"Boy Scouts",
"Top Scout",
"Scout - Freeform",
"Corsair - Freeform",
"Cloak",
"Carrier Pigeons",
"Carrier",
"Interceptor",
"Arbiter - Freeform",
"Archon - Freeform",
"Dark Archon",
"Hover",
"Top Kim Jisoo (BLACKPINK)",
"Top Jennie Kim",
"Top Park Chaeyoung | Rosé",
"Top Lalisa Manoban | Lisa",
"Academy Era",
"Nuoding Academy",
"Basketball",
"Olympics",
"Winter Olympics",
"Summer Olympics",
"NEET",
"BAMF Pepper Potts",
"Nervousness",
"NERV - Freeform",
"Neon Genesis Evangelion References",
"Africa",
"Europe",
"Pre-Europe",
"United States",
"United Kingdom",
"Lance of Longinus | Spear of Destiny",
"Plugsuits",
"Belieber",
"Alternate Universe - Gods & Goddesses",
"Gods",
"Old Gods",
"Trickster Gods",
"Legos",
"Pantyhose",
"Sex on Furniture",
"Furniture",
"IKEA Furniture",
"Busking",
"Guitars",
"Air Guitars",
"Drums",
"Currency",
"London",
"221B Baker Street",
"Baker Street",
"Red Cape",
"Cross-Time Caper",
"Tooth-Rotting Fluff",
"Tooth Fairies",
"Buffalo Sabres",
"Toothache",
"Saber Tooth",
"Cat Ears",
"Cat Puns",
"Herding Cats",
"Woolly Mammoths - Freeform",
"National Geographic",
"Flintstones - Freeform",
"Microscope",
"Twin Peaks References",
"Sweet Valley High - Freeform",
"Archeology",
"Doctor Dolittle - Freeform",
"Alzheimer's Disease",
"Dementia",
"Fossils",
"Race",
"Racism",
"Racist Language",
"Ableism",
"Ableist Language",
"Wardrobe Malfunction",
"Pompoir",
"Plant Sex",
"Plants",
"Pitcher Plant",
"Cupcakes",
"Plates",
"Bowls - Freeform",
"Testicular Orgasm",
"Prostatic Orgasm",
"Urethral orgasm",
"Tortoise",
"Go Fish",
"Fish Sex",
"Swamp",
"Marshes",
"Bogeyman",
"Bog - Freeform",
"Bayou",
"Pond",
"Lake",
"Kangaroo",
"Platypuses",
"Doorjamb",
"Abandonment",
"Academia",
"Academy",
"Affection",
"Affairs",
"Extramarital Affairs",
"Affectionate Dean Winchester",
"Aged-Up Character(s)",
"Age Difference",
"Age Regression/De-Aging",
"Coming of Age",
"Age Play",
"Non-Sexual Age Play",
"Old Age",
"First Age",
"Shounen-ai",
"Shoujo-ai",
"Anachronistic",
"Alternate Universe of an Alternate Universe",
"An X-File Case",
"AO3 1 Million",
"AO3 Tags - Freeform",
"Raised Apart",
"Apes & Monkeys",
"Aquariums",
"Aquaphobia",
"Aquaria",
"Arachnophobia",
"Spit As Lube",
"Come as Lube",
"Crew as Family",
"Blood As Lube",
"Food as a Metaphor for Love",
"Undercover as Married",
"Undercover As Gay",
"Late at Night",
"Lust at First Sight",
"Don't Try This At Home",
"Avalanches",
"Award Winners",
"Awards",
"Academy Awards",
"Award Nominees",
"Awards Presentation",
"Babbling",
"Alternate Universe - BDSM",
"Other Additional Tags to Be Added",
"To Be Continued",
"Could Be Canon",
"Be Careful What You Wish For",
"Meant To Be",
"Boys Will Be Boys",
"Alternate Universe - Beach",
"To Be Edited",
"BFFs",
"Bi-Curiosity",
"Bible",
"Biblical Scripture References (Abrahamic Religions)",
"Biblical Reinterpretation",
"Bi-Gender Character(s)",
"Biblical Allusions (Abrahamic Religions)",
"Bi-Gender",
"Biblical Themes (Abrahamic Religions)",
"Bi-Gender Relationships",
"Bible Kink",
"Fade to Black",
"Black Character(s)",
"Alternate Universe - Boarding School",
"Board Games",
"Monopoly (Board Game)",
"Bubble Bath",
"Bubblegum",
"Bubble Wrap",
"Inspired By Tumblr",
"Inspired by Fanfiction",
"Inspired by Fanart",
"Inspired by Art",
"Inspired by Poetry",
"Inspired by Roleplay/Roleplay Adaptation",
"Inspired by A Christmas Carol",
"Inspired by Twitter",
"Inspired by...",
"Cabarets",
"CCTV",
"Everyone Needs A Hug",
"Not A Fix-It",
"Alternate Universe - Always a Different Sex",
"B-Movies",
"Cecaelias",
"Claiming",
"Public Claiming",
"Co-workers",
"Emotional Roller Coaster",
"Roller Coasters",
"Coats",
"Coach Victor Nikiforov",
"Sherlock's Coat",
"Coalition",
"Coach/Player Relationship",
"Coach Katsuki Yuuri",
"Coaches",
"Crack Treated Seriously",
"Alternate Universe - Crack",
"Crack Relationships",
"Crack and Angst",
"Dark Crack",
"Christmas Crack",
"Cthulhu Mythos",
"Cult of Cthulhu",
"Cuckquean",
"Cosmic Cube",
"Dacryphilia",
"Dead Dove: Do Not Eat",
"Presumed Dead",
"Talking To Dead People",
"Nobody is Dead",
"Everyone is Dead",
"Diabetes",
"Djinni & Genies",
"Alternate Universe - Genie/Djinn",
"How Do I Tag",
"Aliens Made Them Do It",
"Magic Made Them Do It",
"Nonnies Made Me Do It",
"Do-Over",
"Something Made Them Do It",
"Drugs Made Them Do It",
"Bad Guys Made Them Do It",
"Faeries Made Them Do It",
"Drabble",
"Drabble Collection",
"Dubious Ethics",
"Dubiously Consensual Blow Jobs",
"Implied/Referenced Dubious Consent",
"Dubious Consent Due To Identity Issues",
"Dubcon Kissing",
"Dubious Consentacles",
"Dubcon Cuddling",
"Dubcon or Noncon Moirallegiance",
"Pale Romance | Moirallegiance",
"Unrequited Moirallegiance",
"Power Dynamics",
"Pack Dynamics",
"Team Dynamics",
"Non-Traditional Alpha/Beta/Omega Dynamics",
"Alpha/Beta/Omega Dynamics",
"Family Dynamics",
"Hair Dyeing",
"No Alpha/Beta/Omega Dynamics",
"Team Nice Dynamite",
"E-mail",
"Getting to Know Each Other",
"Made For Each Other",
"The Echo Chamber",
"Butterfly Effect",
"Bleeding Effect",
"Side Effects",
"Status Effects",
"Eggpreg",
"Eggnog",
"Easter Egg Hunt",
"Premature Ejaculation",
"Female Ejaculation",
"Forced Ejaculation",
"Epic",
"Epic Friendship",
"Epic Bromance",
"Epic Love",
"Epic Fail",
"Ephebophilia",
"Epic Poetry",
"Equestrian",
"Sexual Equality",
"Canon Era",
"War Era",
"Escapism",
"Escape Pod",
"Free! Eternal Summer",
"Christmas Eve",
"Don't Examine This Too Closely",
"Medical Examination",
"Exactly What It Says on the Tin",
"Ex Sex",
"Eye Trauma",
"Eyes",
"Eye Sex",
"Eye Contact",
"Blue Eyes",
"Forced Eye Contact",
"Eye Gouging",
"Eyeliner",
"Green Eyes",
"Black Eye",
"Eye Color",
"Eye Licking",
"Mint Eye",
"Eyebrows",
"Fables - Freeform",
"Fear",
"Fear of Death",
"Fear Play",
"Fear of Discovery",
"Future Fic",
"Kid Fic",
"Prompt Fic",
"Case Fic",
"Gift Fic",
"Flash Fic",
"Comment Fic",
"Mission Fic",
"Creature Fic",
"Band Fic",
"Curtain Fic",
"Id Fic",
"Cabin Fic",
"Self-Flagellation",
"Foe Yay",
"Fog",
"Brain Fog",
"Fpreg",
"Kung Fu",
"Metal Gear Solid 3: Snake Eater",
"Metal Gear Solid 4: Guns of the Patriots",
"Metal Gear Solid V: The Phantom Pain",
"Metal Gear 2: Solid Snake",
"Metal Gear References",
"Vertical Maneuvering Gear",
"Studio Ghibli References",
"Gladiators",
"Gnosticism",
"Gnolls",
"I Will Go Down With This Ship",
"This Is Not Going To Go The Way You Think",
"Goalies",
"Gotta Go Fast",
"Seasonal Spirits and Guardians",
"Alternate Universe - Guardian Angels",
"Headcanon",
"Headaches & Migraines",
"Headcanon Accepted",
"Head Shaving",
"Hubris",
"I Don't Even Know",
"I Wrote This Instead of Sleeping",
"I'm Sorry",
"I Tried",
"Why Did I Write This?",
"What Have I Done",
"I Can't Believe I Wrote This",
"What Was I Thinking?",
"I'm Going to Hell",
"I Blame Tumblr",
"Ibuprofen",
"Bad Ideas",
"Idealism",
"What-If",
"If you only read one work by me",
"Imaginary Friends",
"Imagine your OTP",
"Work In Progress",
"Mating Cycles/In Heat",
"Moving In Together",
"Snowed In",
"Kissing in the Rain",
"iPhones",
"Everyone Is Gay",
"This Is STUPID",
"Everyone Is Alive",
"Fix-It of Sorts",
"Time Travel Fix-It",
"Post-Canon Fix-It",
"It Gets Worse Before It Gets Better",
"I Ship It",
"Reunited and It Feels So Good",
"Civil War Fix-It",
"Protective Jiang Yanli",
"Jiangshi",
"Ghost Jiang Yanli",
"Jiang Cheng | Jiang Wanyin Gets a Hug",
"First Time Blow Jobs",
"Blow Jobs in a Car",
"Under-Desk Blow Jobs",
"Awkward Blow Jobs",
"Jock Straps",
"Don't Judge Me",
"Judaism",
"Don't Judge",
"Koalas",
"Kobolds",
"Laboratories",
"Lab Sex",
"Next-Gen Labour",
"Labor Unions",
"Alternate Universe - Laboratory",
"New Labour",
"Lab Bromance",
"LGBTQ Themes",
"LGBTQ Character",
"LGBTQ Character of Color",
"LGBTQ Female Character",
"Canon LGBTQ Character",
"LGBTQ Female Character of Color",
"Canon LGBTQ Male Character",
"Llamas",
"Drama Llama",
"Llamacide",
"LSD",
"Self-Lubrication",
"Lube",
"No Lube",
"Flavored Lube",
"S&M",
"Mild S&M",
"McDonald's",
"Please Don't Hate Me",
"Forgive Me",
"Please Don't Kill Me",
"For Me",
"Senpai Notice Me",
"MMORPGs",
"Mud",
"Jack-o'-lanterns",
"Obedience",
"Curse of Obedience",
"Occult",
"Odd",
"Out of Character",
"Denial of Feelings",
"Aftermath of Torture",
"Alternate Universe - Office",
"Stream of Consciousness",
"Oil",
"Oil Gland Kink",
"Okay Ending",
"Old Friends",
"Growing Old Together",
"Older Woman/Younger Woman",
"Growing Old",
"Death from Old Age",
"Oops",
"Spare Oom",
"Open Relationships",
"Open to Interpretation",
"Open Marriage",
"Soap Opera",
"Truth or Dare",
"Oral Fixation",
"Non-Consensual Oral Sex",
"Trick or Treating",
"Consensual But Not Safe Or Sane",
"Oral Knotting",
"Work Contains Fan(s) or Fandom(s)",
"Ouch",
"Starting Over",
"Over the Knee",
"Over the Top",
"Wordcount: Over 100.000",
"Wordcount: Over 10.000",
"Wordcount: Over 1.000",
"Wordcount: Over 50.000",
"Wordcount: Over 200.000",
"Wordcount: Over 20.000",
"Wordcount: Over 150.000",
"Wordcount: Over 30.000",
"Wordcount: Over 500.000",
"Peace",
"Peacekeepers",
"Bad Pick-Up Lines",
"Pick-Up Lines",
"Pi",
"Science Pick-Up Lines",
"Plague",
"The Bad Place",
"Pneumonia",
"Practice Kissing",
"Target Practice",
"Pragmatic Idealism",
"Alternate Universe - Practical Magic Fusion",
"Checking Practice",
"Pseudoscience",
"Pseudo-History",
"Pseudonyms",
"Pseudo-Vampire",
"Pseudepigrapha",
"Bars and Pubs",
"Puberty",
"PWP without Porn",
"Quad Jumps (Figure Skating)",
"Quad Axel (Figure Skating)",
"R&R",
"Rabies",
"Worth Re-Reading",
"Re-Education",
"Rubber Ducks",
"Ribbons",
"Road Trips",
"Alternate Universe - Road Trip",
"Not RPF",
"Past Relationship(s)",
"Relationship(s)",
"Original Female Character(s) - Freeform",
"Minor Character(s)",
"Loss of Parent(s)",
"Assassination Attempt(s)",
"Sea Monsters",
"Sea of Simulation",
"Mystery Shack",
"Siblings",
"Sick Character",
"Sibling Bonding",
"Sibling Love",
"Protective Siblings",
"Sibling Rivalry",
"Half-Sibling Incest",
"Step-siblings",
"Alternate Universe - Small Town",
"Hurts So Good",
"Sobbing",
"So Wrong It's Right",
"Sobriety",
"Alternate Universe - Space",
"Space Pirates",
"Lesbians in Space",
"Alternate Universe - Space Opera",
"Squabbling",
"Boy Squad",
"Dom/sub",
"Dom/sub Undertones",
"Dom/sub Play",
"Come Swallowing",
"Swans",
"Swan Song",
"Alternate Universe - Teachers",
"Alternate Universe - Student/Teacher",
"Teabagging",
"To Read",
"Strangers to Lovers",
"References to Depression",
"To Rec",
"To Comment",
"Hate to Love",
"Slow To Update",
"Post-Trade",
"Rough Trade",
"Trade Deadline",
"Pre-Trade",
"TV Tropes",
"TV News",
"The Art of War - Sun Tzu",
"Uber",
"UFOs",
"Ugly Holiday Sweaters",
"Ugly Sweaters",
"Ugly Duckling",
"Umbrellas",
"Break Up",
"Post-Break Up",
"Growing Up",
"Waiting For Update",
"Hook-Up",
"Growing Up Together",
"Dress Up",
"Urban Fantasy",
"Alternate Universe - Urban Fantasy",
"Urban Legends",
"Recreational Drug Use",
"Inappropriate Use of the Force",
"Safeword Use",
"Medicinal Drug Use",
"Accidental Drug Use",
"Underage Substance Use",
"Christmas Vacation",
"Viagra",
"Vodka",
"Voice Acting",
"Angels vs. Demons",
"Gryffindor vs. Slytherin Rivalry",
"Humans vs. Werewolves",
"Avengers vs X-men",
"Hunters Vs. Pack",
"Pirates vs Ninjas",
"Vulnerability",
"Vulnerable Sherlock",
"Deja Vu",
"This Is Why We Can't Have Nice Things",
"Strong Woman/Weak Man",
"We are all Irrelevant.",
"Timeline What Timeline",
"Not What It Looks Like",
"Continuity What Continuity",
"Whales",
"Wolf Pack",
"Bad Wolf",
"Wolf Instincts",
"Wolf Sex",
"Bad Wolf Bay",
"Wolfed Out Sex",
"Wraith",
"Wraith Feeding",
"WTF",
"Xeno",
"Xenolinguistics",
"Bottom Wang Yi Bo/Top Xiao Zhan | Sean",
"Yggdrasil - Freeform",
"Yoga",
"A-Z",
"Zebras",
"Wordcount: 100",
"Diplodocus",
"Ankylosaurus - Freeform",
"Dimetrodon",
"Stegasaurus",
"Allosaurus",
"Mastodon",
"Sauropods",
"Theropods",
"Iguanadon",
"Duck Bill",
"Archaeoptyrex",
"Pterosaur",
"Pterodactyl",
"Shrew",
"Ichthyosaurus",
"Kodiak Bear",
"Eohippus",
"Flute - Freeform",
"Guqin",
"Guzheng",
"Hundred Acre Wood",
"Surgery",
"Brain Surgery",
"Circus",
"The Lord of the Rings References",
"Pirates of the Caribbean References",
"Advanced Dungeons and Dragons",
"Dungeons & Dragons References",
"Dungeons & Dragons Elements",
"Dungeons & Dragons Spell Mechanics",
"Movie: Dawn of the Planet of the Apes (2014)",
"Movie: War of the Planet of the Apes (2017)",
"Movie: Rise of the Planet of the Apes (2011)",
"Zeliard",
"Silpheed",
"Ping-Pong",
"Prehistorik",
"Final Fantasy XIV References",
"Eorzea (Final Fantasy XIV)",
"Alternate Universe - Wreck-It Ralph Fusion",
"Song: Hakuna Matata (Disney)",
"Disney References",
"Disney",
"Disney World & Disneyland",
"Disney Movies",
"Disney Songs",
"Inspired by Disney",
"Disney Multiverse",
"Disney Parody",
"Keyblades (Kingdom Hearts)",
"Miqo'te (Final Fantasy XIV)",
"Hyur (Final Fantasy XIV)",
"Elezen (Final Fantasy XIV)",
"Roegadyn (Final Fantasy XIV)",
"Lalafell (Final Fantasy XIV)",
"Wing Grooming",
"Wings",
"Angel Wings",
"Wing Oil",
"Kilrathi",
"Yellow Pillow",
"Yellow Scarves",
"Au Ra (Final Fantasy XIV)",
"Hrothgar (Final Fantasy XIV)",
"Viera (Final Fantasy)",
"British",
"British English",
"British Slang",
"British Comedy",
"British Character",
"British Empire",
"British Museum",
"British Politics",
"British Military",
"Americans",
"Americanisms",
"American History",
"American Revolution",
"American Politics",
"American Civil War",
"Shotgunning",
"Shotgun",
"Terminator (Movies) References",
"Guns",
"Gunshot Wounds",
"Shooting Guns",
"Girls with Guns",
"Young Guns",
"Excellent",
"Arkanoid",
"Breakout",
"Alley Sex",
"Alley Cat - Freeform",
"Ghosts",
"Sexual Content",
"Implied Sexual Content",
"Sexual Tension",
"Unresolved Sexual Tension",
"Mild Sexual Content",
"Resolved Sexual Tension",
"Awkward Sexual Situations",
"Smart Is The New Sexy",
"Next Generation",
"Generation Gap",
"Genealogy",
"Asexual Character",
"Asexuality",
"Asexual Relationship",
"Asexuality Spectrum",
"Bisexual Female Character",
"Bisexual Character",
"Parthenogenesis",
"Asexual Reproduction",
"Bargaining",
"Charity Auctions",
"Auction",
"Bachelor Auction",
"Auctions",
"D/generation",
"Isolation",
"Geographical Isolation",
"Aliens",
"Alien Biology",
"Alien Culture",
"Alien Sex",
"Alien Cultural Differences",
"Alien Planet",
"Alien Invasion",
"Alien Abduction",
"Alien Gender/Sexuality",
"Alien Flora & Fauna",
"Tarzan References",
"Tarzan - All Media Types references",
"Ducks",
"Duck Hunt (Video Game) references",
"Ghost Sex",
"Ghost Drifting",
"魔界村 | Makaimura | Ghosts 'n Goblins (Video Games) references",
"The Jungle Book - All Media Types references",
"Inspired by E.T.: The Extra-Terrestrial (1982)",
"Hitchhiker's Guide to the Galaxy References",
"Infanticide",
"Accidental Baby Acquisition",
"Baby Dumping",
"Sitcom",
"Hostage Situations",
"Comedy of Errors",
"Jetsons",
"Playgrounds",
"Power Play",
"Temperature Play",
"Impact Play",
"Sensation Play",
"Trees",
"Tree Sex",
"Tree Houses",
"Sacred Trees",
"Men in Black (Movies) References",
"The Simpsons References",
"Indian Character",
"Slurs",
"Video",
"Webcam/Video Chat Sex",
"Video Cameras",
"Super Mario References",
"Choose Your Own Adventure",
"Inspired by Kimetsu no Yaiba",
"BEASTARS References",
"Naruto References",
"Graphic Description of Corpses",
"Corpses",
"Corporate Espionage",
"Evil Corporations",
"Demon/Human Relationships",
"Demon Blood",
"Hokage",
"References to Star Wars: Original Trilogy",
"Star Wars Sequel Trilogy references",
"One Piece References",
"Futanari"
);
?>

        
        <title>Sexy Times Generator</title>
        
        <style type="text/css">
            body{
                font: normal 95%/160% 'Lucida Grande','Lucida Sans Unicode','GNU Unifont',Verdana,Helvetica,sans-serif;
                background: #fff;
                overflow-x: hidden;
                margin: 0;
                padding: 0;
                color: #2a2a2a;
            }
            
            #top{
                width: 100%;
                margin: 0.5%;
            }
            
            .left{
                font: normal 180% 'Georgia';
                color: #980000;
            }
            
            #top a:link, #top a:visited{
                color: #980000;
                text-decoration: none;
                border-bottom: none;
            }
            
            #top a:hover, #top a:focus, #top a:active{
                background: none;
                color: #980000;
            }
            
            #redborder{
                clear: both;
                background: #900 url('red.png') repeat-x;
                width: 100%;
                height: 32px;
                box-shadow: inset 0 -6px 10px rgb(0 0 0 / 35%), 1px 1px 3px -1px rgb(0 0 0 / 25%), inset 0 -1px 0 rgb(0 0 0 / 85%);
            }
            
            img.logo{
                height: 38px;
                 vertical-align: text-bottom;
            }
            
            h1{
                font: normal 220% 'Georgia', serif;
                font-weight: none;
                text-align: center;
            }
            
            #container{
                box-shadow: 1px 1px 5px #aaa;
                width: 80%;
                margin: 4% auto;
                padding: 2%;
            }
            
            a:link, a:visited{
                color: #111;
                border-bottom: 1px dotted;
                text-decoration: none;
            }
            
            a:hover, a:focus, a:active{
                background: #900;
                color: #fff;
            }
            
            .addt{
                    min-width: 10.5em;
                    width: 25%;
                    float: left;
                    clear: left;
            }
            
            .tags{
                    width: 72.5%;
    float: left;
    margin: 0 0 .643em;
    font: normal 160%/160% 'Lucida Grande','Lucida Sans Unicode','GNU Unifont',Verdana,Helvetica,sans-serif;
            }
            
            .tags b{
                font-weight: normal;
                border-bottom: 1px dotted;
            }
            
            #blurb{
                font: normal 100%/150% 'Lucida Grande','Lucida Sans Unicode','GNU Unifont',Verdana,Helvetica,sans-serif, sans-serif;
                border-bottom: 1px solid;
                padding-bottom: 1%;
            }
            
            #prompts{
                margin: 4% auto 7%;
            }
            
            input[type="button"] {
    font: normal 150% 'Georgia', serif;
    color: #111;
    text-align: center;
    border: none;
    margin: 15% auto 5%;
    display: block;
    padding: 1%;
            }
            
            input[type=button]:hover{
cursor: pointer;
background: #900;
color: #fff;
}

#footer{
    border-top: 1px solid;
    padding: 3% 0 2%;
    font: normal 100% 'Georgia';
    text-align: center;
}

@media only screen and (max-width: 960px) {

html {
-webkit-text-size-adjust: none;
}

#container{
    width: 95%;
    margin: 3% auto;
    padding: 2%;
}

.left {
    font: normal 170% 'Georgia';
}

#blurb {
    font: normal 90%/150% 'Lucida Grande','Lucida Sans Unicode','GNU Unifont',Verdana,Helvetica,sans-serif, sans-serif;
    border-bottom: 1px solid;
    padding-bottom: 2vh;
}

#prompts {
    margin: 4vh auto;
}

.tags{
    padding-left: 10px;
    width: auto;
    font: normal 120%/160% 'Lucida Grande','Lucida Sans Unicode','GNU Unifont',Verdana,Helvetica,sans-serif;
    margin-bottom: 5vh;
}

input[type="button"]{
        margin: 0 auto 5vh;
    padding: 3%;
}

#footer{
    padding: 2vh 0;
}

}
        
        </style>
        
        </head>
        
        <body>
            
        <div id="top">
            
            <div class="left">
               <img src="ao3aroceu2.png" class="logo"> the sexy times with wangxian tag generator
            </div>
            
        </div>
        
        <div id="redborder"></div>

       <div id="container">    
       
                       <h1>Sexy Times with...</h1>
            
            <div id="content">

            <div id="blurb"><p>From the tags on the late and great Sexy Times With Wangxian (<a href="https://fanlore.org/wiki/Sexy_times_with_Wangxian">read more</a>), this generator will give you 3 to 5 additional tags that it used to have. Feel free to contact me if there are any problems!</p>
            
            <p>All tags are listed as they were originally typed/tagged on the fic&mdash;I have not corrected any typoes.</p>
            
                <div id="prompts">
                    
                    <div class="addt">Additional Tags: </div>
<div class="tags"><?php
$rand_keys = array_rand($sexytimes, $i=rand(3,5));
echo "<b>";
echo $sexytimes[$rand_keys[0]] . "</b>, ";

if($i == 2){
    echo "<b>";
    echo $sexytimes[$rand_keys[1]];
    echo "</b>";
}
else{
    for($c = 1; $c < $i - 1; ++$c){
        echo "<b>";
        echo $sexytimes[$rand_keys[$c]] . "</b>, ";
    }
    echo "<b>";
    echo $sexytimes[$rand_keys[$i - 1]];
    echo "</b>";
}
?></div>

</div>

<p><input type="button" onclick="location.reload();" value="Generate another?" /></p>


</div>

<div id="footer">
    &copy; <?php echo date("Y"); ?> &bull; <a href="/generators/">generators</a> &bull; <a href="https://aroceu.com">contact</a>
    </div>

    </div>
    
    </div>

    

    </body>

