<?php
$all = array("fisting",
"branding",
"piercing",
"tattooing",
"bruising or bitemarks",
"aphrodisiacs",
"drugs",
"food",
"temperature play",
"suspension",
"deepthroating",
"spanking/paddling",
"petplay",
"orgasm denial",
"teasing",
"tickling",
"object penetration (toys – worn under clothes)",
"object penetration (toys – not worn)",
"object penetration (objects not designed for sex)",
"bondage (held down)",
"bondage (immobility)",
"bondage (wrist restraints)",
"bondage (full body)/hojojutsu",
"tentacles",
"crossdressing (outerwear)",
"crossdressing (underwear/lingerie)",
"foot fetish",
"hand fetish",
"ear fetish",
"armpit fetish",
"finger fetish",
"knee fetish",
"glory holes",
"bukkake/facials",
"watersports",
"shaving",
"sensory deprivation (sight)",
"sensory deprivation (sound)",
"sensory deprivation (touch)",
"sensation play",
"gags + blindfolds + bondage",
"breathplay",
"gags",
"silence",
"barebacking",
"humiliation (public)",
"humiliation (private)",
"humiliation (verbal)",
"obedience",
"dirty talk",
"candle play",
"gangbang",
"orgy",
"double penetration (one hole)",
"double penetration (two holes)",
"consent play",
"flogging",
"caning",
"knifeplay",
"gunplay",
"roleplay/au (authority figures)",
"roleplay/au (historical)",
"roleplay/au (domestic/tradesmen)",
"roleplay/au (prostitute)",
"roleplay/au (master/slave)",
"roleplay/au (ddlg)",
"roleplay/au",
"virginity/celibacy",
"costumes",
"striptease",
"genital torture",
"electricity",
"enemas",
"fucking machines",
"nippleplay",
"leather/latex",
"locked up",
"voyeurism",
"exhibitionism",
"public sex",
"outdoor sex",
"phonesex",
"Phone Sex Operator",
"rimming",
"felching",
"vehicular",
"road head",
"plushies/furries",
"snowballing",
"cockrings",
"rough sex",
"kama sutra (extreme positions)",
"film/photography",
"begging",
"sleepy/unconscious",
"writing on the body",
"washing/cleaning each other",
"pegging/strap-ons",
"anonymous sex",
"chastity devices",
"mirrors",
"penance/punishment",
"docking",
"sexswap",
"praise kink",
"tentacles",
"knotting",
"size kink",
"heats/mating cycles",
"boot worship",
"omorashi",
"figging",
"iceplay",
"sadism",
"masochism",
"d/s",
"cockwarming",
"sounding",
"service kink",
"dacryphilia (crying kink)",
"scent kink",
"voice fetish",
"vore",
"cannibalism",
"69",
"intercrural sex",
"intergluteal sex",
"comeplay",
"collaring",
"lactation",
"impregnation/breeding",
"inflation",
"fingering come back in",
"dryfucking",
"ankle fetish",
"wrist fetish",
"masseuse",
"edging",
"anal beads",
"fleshlights",
"oviposition",
"creature/alien/monster",
"frottage",
"riding",
"topping from the bottom",
"facefucking",
"body worship",
"sex robot",
"Fake Relationship",
"Accidental Marriage",
"Arranged Marriage",
"Modern Royalty AU",
"Regency AU",
"High School AU",
"University AU",
"Teacher or Professor AU",
"Vampires",
"Werewolves",
"Apocalypse",
"Canon Divergence",
"Post-Canon/Futurefic",
"Pre-Canon",
"Sharing A Bed",
"Trapped Together",
"Bonded (physical distance causing pain)",
"Bonded (telepathy)",
"Bonded (telepathy & physical distance causing pain)",
"Handcuffed/Physically Bound Together",
"Matchmaking",
"Crossover Fusion",
"Fix-It Fic",
"Bodyswap",
"Coffee Shop AU",
"Spy AU",
"Criminal Syndicate AU",
"Casefic/Mystery",
"Economical Class Difference AU",
"Hookerfic",
"Hurt/Comfort",
"Angst",
"Flangst",
"Wingfic",
"HDM Daemon AU",
"5+1",
"Holidayfic",
"Reincarnation AU",
"Time Travel",
"Character Study",
"Amnesiafic",
"Magical Connection/Telepathy",
"Presumed Dead",
"Doppelgangers",
"Animal Transformation",
"Missing Scene/Episode Tag",
"Role Reversal",
"Mirror Universe",
"Bets/Wagers",
"Oh Snap It's You Again",
"Oh Snap It's You Again (& you got hot)",
"Utopia/Dystopia AU",
"Competitive Sport AU",
"The Bachelor/Dating Show",
"Game Show",
"Bachelor Auction",
"Immortals",
"Break Up Make Up",
"Roadtrip",
"Soulmate Identifying Marks",
"Fake Out Make Out",
"Groundhog Day/Timeloop",
"Enemies with Benefits",
"Friends with Benefits",
"Childhood Friends (AU)",
"Met Later In Canon AU",
"Student/Teacher AU",
"Age Difference AU",
"Age Difference Due To Regression",
"De-aging Kidfic",
"Femslash AU (or slash AU if inapplicable)",
"Independent Business Owner",
"Character Death Fix",
"Bakery/Chef/Restaurant AU",
"Ghostfic",
"Afterlife",
"Fever Dream",
"Angel/Human",
"Angel/Demon",
"Demon/Human",
"Superpowers AU",
"Superhero AU",
"Didn't Know They Were Dating",
"Space AU",
"Pirate AU",
"Steampunk AU",
"Epistolary",
"Twin AU",
"Fandom/Internet Celebrity AU",
"Recursive Fic",
"Identity Porn/Comedy of Errors",
"Kissing Practice",
"Locked in a Room",
"<a href='https://fanlore.org/wiki/Let_Me_Be_Weak,_Let_Me_Sleep'>Let Me Be Weak, Let Me Sleep</a>",
"Catboy/Kemonomimi",
"Merpeople/Selkie AU",
"Mythology AU",
"Neighbors AU",
"Roommates AU",
"Magical Tattoos",
"Priest AU",
"Prison AU",
"Stripper AU",
"Seven Minutes In Heaven",
"Spin the Bottle",
"Serial Killers",
"Stranded on Desert Island",
"Kids AU (characters as kids)",
"Assigned Mentor/Tutor",
"Soulmate AU",
"Marriage of Convenience",
"Hospitalfic",
"Forced Obedience/Mind Control",
"Robots",
"Universe Alteration",
"Denialfic",
"Fairytale AU",
"Boarding School AU",
"Summer Love",
"Drabble Collection",
"Non-Linear",
"Five Things/Times",
"First Love",
"Gay Chicken",
"Sickfic",
"Bars/Clubs",
"Thief AU",
"Curseworkers AU",
"Battle Royale/Hunger Games AU",
"Boss/Assistant AU",
"Bystander POV",
"Secret Admirers/Anonymous Notes",
"In Vino Veritas",
"Massages",
"Secret Santa",
"Magic/Nonmagic AU",
"Hogwarts AU",
"Competitive Rivals",
"Beachfic",
"Language Barrier",
"Cultural Barrier",
"Omegaverse",
"Dominance Hierarchy AU",
"BDSM",
"Kink Negotiation",
"Mpreg",
"Sex Slaves",
"Genderfuck/Sexswap (wake up with not-assigned-at-birth genitals)",
"Pornstar AU",
"Incest AU",
"Rape Recovery",
"Harem AU",
"Hanahaki Disease",
"Camgirl AU",
"Disabilityfic",
"Terminal Illness",
"War AU",
"Possessive",
"Anthropomorphic",
"Crack Taken Seriously",
"Shapeshifter",
"Need To Be Taught (Ballroom) Dancing",
"Fraternity/Sorority",
"Bikers",
"Fantastical or Supernatural Creature/Human",
"Astronaut/Space Explorer",
"Kid Teacher",
"High School Teacher",
"University Professor",
"Babysitter",
"Gardener",
"Chef",
"Baker",
"Gangs",
"Mafia/Yakuza",
"Conmen",
"Spy",
"Priest",
"Hitman/Assassin",
"Low-Paying Food Service",
"Pet Trainer",
"Stripper",
"Hooker/rentboy",
"Celebrity",
"Piano Teacher",
"Dancer/Ballet",
"Orchestral Musician",
"Pop Star",
"Porn Star",
"Camgirl",
"Professional Athlete",
"Lawyer",
"Receptionist/Secretary",
"Office",
"Freelance Writer",
"Freelance Artist",
"Roadie",
"Playboy/playgirl",
"Personal Assistant",
"Programmer",
"Theater Actor/Tech Crew",
"Ceramicist/Carpenter",
"Professional/Competitive Gamer",
"Disneyworld Character",
"Olympic Athlete",
"Graphic Designer",
"Web Developer",
"Photographer",
"Retail",
"Bookshop",
"Librarian",
"Call Service",
"Firefighter",
"Tech Support/IT",
"Detective/Private Investigator",
"Farmer",
"Lifeguard",
"Construction Worker",
"Other Animal Career (pet store, cat cafe, zookeeper, etc.)",
"Marine Biologist",
"Astronomer",
"Customer Service",
"Space Thief",
"Sex shop",
"Political/government",
"Environmental Activist",
"Social Activist",
"Royalty",
"Doctor",
"Nurse",
"Veternarian",
"Barista",
"Curseworkers ",
"Hired Maid",
"Superhero",
"Pirate",
"Space Pirate",
"Internet Personality",
"Vlogger/Blogger",
"Cosplayers",
"Knight/Guard",
"Bodyguard",
"Serial Killer",
"Single Parent Kidfic",
"Academic Tutor",
"Etiquette Tutor",
"Bartender",
"Masseuse",
"Curator",
"Famous Critic",
"Yoga Instructor",
"Personal Trainer",
"Masseuse",
"Architect",
"Sex Therapist",
"Dentist",
"Hotel Maid",
"Barber/Stylist",
"Author/Editor",
"Public/Human Relations",
"Flight Attendant",
"Flower Shop",
"Tattoo Artist",
"Ghostwriter",
"Car Mechanic",
"Vigilante",
"Black Ops",
"Ghost/Demon Hunters",
"Hacker",
"Street Magician",
"Magician/Assistant",
"Environmental Researcher",
"Historical Researcher",
"Painter",
"Wedding Planner",
"Sextape",
"Established Relationship",
"Supervillain",
"Canon Compliant",
"Universe Hopping",
"Camping/Hiking",
"Journalist",
"Bribery",
"Magical Wish Fulfillment/Genies",
"Delinquent",
"Academic Tutor",
"Etiquette/Skill Mentor",
"Precognition/Future Sight",
"Mistletoe",
"Summer Camp",
"PTSD/Trauma",
"Accidental Baby Acquisition",
"Influencers",
"Art Thief/Heist",
"Fuck or Die",
"Social Media Influencer/Content Creator/Streamer",
);

?>