<?php
$careers = array("Astronaut/Space Explorer",
"Teacher",
"Professor",
"Babysitter",
"Gardener",
"Chef",
"Baker",
"Gangs",
"Mafia/Yakuza",
"Conmen",
"Spy",
"Priest",
"Hitman/Assassin",
"Low-Paying Food Service",
"Pet Trainer",
"Stripper",
"Hooker/rentboy",
"Celebrity",
"Piano Teacher",
"Dancer/Ballet",
"Musician",
"Pop Star",
"Porn Star",
"Camgirl",
"Professional Athlete",
"Lawyer",
"Receptionist/Secretary",
"Office",
"Freelance Writer",
"Freelance Artist",
"Roadie",
"Playboy/playgirl",
"Personal Assistant",
"Programmer",
"Theater Actor/Tech Crew",
"Ceramicist/Carpenter",
"Pro/Competitive Gamer",
"Olympic Athlete",
"Web Designer",
"Photographer",
"Grocery Store",
"Retail/Cashier",
"Bookshop",
"Librarian",
"Call Service",
"Phone Sex Operator",
"Firefighter",
"Tech Support/IT",
"Detective/PI",
"Farmer",
"Lifeguard",
"Construction Worker",
"Animal Care (pet store/zoo)",
"Marine Biologist",
"Astronomer",
"Customer Service",
"Space Thief",
"Sex Shop",
"Political/government",
"Environmental Activist",
"Social Activist",
"Royalty",
"Doctor",
"Nurse",
"Veternarian",
"Barista",
"Game Show Contestant",
"Hired Maid",
"Superhero",
"Supervillain",
"Independent Business Owner",
"Pirate",
"Space Pirate",
"Internet Personality",
"Social Media Influencer/Content Creator/Streamer",
"Vlogger/Blogger",
"Cosplayers",
"Knight/Guard",
"Bodyguard",
"Serial Killer",
"Single Parent",
"Academic Tutor",
"Etiquette Tutor",
"Bartender",
"Masseuse",
"Curator",
"Famous Critic",
"Yoga Instructor",
"Personal Trainer",
"Architect",
"Sex Therapist",
"Dentist",
"Hotel Maid",
"Barber/Stylist",
"Author/Editor",
"Public/Human Relations",
"Flight Attendant",
"Flower Shop",
"Tattoo Artist",
"Ghostwriter",
"Car Mechanic",
"Vigilante",
"Black Ops",
"Ghost/Demon Hunters",
"Hacker",
"Street Magician",
"Magician/Assistant",
"Environmental Researcher",
"Historical Researcher",
"Painter",
"Wedding Planner",
"Journalist",
"Influencers");
?>