<?php
$fandom = array("Fake Relationship",
"Accidental Marriage",
"Arranged Marriage",
"Royalty AU",
"Regency AU",
"High School AU",
"University AU",
"Teacher or Professor AU",
"Vampires",
"Werewolves",
"Were-creature",
"Apocalypse",
"Zombie Apocalypse",
"Environmental Apocalypse",
"Robot Apocalypse",
"Post-Apocalyptic",
"Canon Divergence",
"Post-Canon/Futurefic",
"Pre-Canon",
"Sharing A Bed",
"Trapped Together",
"Bonded (physical pain)",
"Bonded (telepath/empath)",
"Handcuffed/Physically Bound Together",
"Matchmaking",
"Crossover Fusion",
"Fix-It Fic",
"Bodyswap",
"Coffee Shop AU",
"Spy AU",
"Criminal Syndicate AU",
"Casefic/Mystery",
"Economical Class Difference AU",
"Hookerfic",
"Hitman/Assassin AU",
"Hurt/Comfort",
"Angst",
"Flangst",
"Wingfic",
"HDM Daemon AU",
"5+1",
"Holidayfic",
"Reincarnation AU",
"Time Travel",
"Character Study",
"Amnesiafic",
"Presumed Dead",
"Doppelgangers",
"Animal Transformation",
"Missing Scene/Episode Tag",
"Role Reversal",
"Mirror Universe",
"Bets/Wagers",
"Oh Snap It's You Again",
"Oh Snap It's You Again (& you got hot)",
"Utopia/Dystopia AU",
"The Bachelor/Dating Show",
"Game Show",
"Bachelor Auction",
"Immortals/Gods",
"Roadtrip",
"Soulmate Identifying Marks",
"Groundhog Day/Timeloop",
"Enemies with Benefits",
"Friends with Benefits",
"Childhood Friends [AU]",
"Enemies [AU]",
"Met Later In Canon AU",
"Age Difference AU",
"De-aging Kidfic",
"Hired Maid",
"Femslash/slash AU",
"Independent Business Owner",
"Character Death Fix",
"Bakery/Chef/Restaurant AU",
"Ghostfic",
"Afterlife",
"Fever Dream",
"Angel/Human",
"Angel/Demon",
"Demon/Human",
"Superpowers AU",
"Superhero AU",
"Didn't Know They Were Dating",
"Space AU",
"Space Pirate",
"Space Thief",
"Space Explorer/Astronaut",
"Pirate AU",
"Steampunk AU",
"Epistolary",
"Twin AU",
"Fandom/Internet Celebrity AU",
"Recursive Fic",
"Identity Porn/Comedy of Errors",
"Kissing Practice",
"Locked in a Room",
"Let Me Be Weak, Let Me Sleep",
"Catboy/Kemonomimi",
"Merpeople/Selkie AU",
"Mythology AU",
"Neighbors AU",
"Roommates AU",
"Magical Tattoos",
"Priest AU",
"Prison AU",
"Stripper AU",
"Seven Minutes In Heaven",
"Spin the Bottle",
"Serial Killers",
"Single Parent Kidfic",
"Kidfic",
"Stranded on Desert Island",
"Kids AU",
"Academic Tutor",
"Etiquette/Skill Mentor",
"Soulmate AU",
"Marriage of Convenience",
"Hospitalfic",
"Forced Obedience/Mind Control",
"Robots",
"Universe Alteration",
"Denialfic",
"Fairytale AU",
"Boarding School AU",
"Flower Shop AU",
"Summer Love",
"Drabble Collection",
"Non-Linear",
"Five Things/Times",
"First Love",
"Gay Chicken",
"Sickfic",
"Bars/Clubs",
"Thief AU",
"Battle Royale/Hunger Games AU",
"Boss/Assistant AU",
"Bystander POV",
"Secret Admirers/Anonymous Notes",
"In Vino Veritas",
"Massages",
"Secret Santa",
"Magic/Nonmagic AU",
"Competitive Rivals",
"Beachfic",
"Language Barrier",
"Cultural Barrier",
"Omegaverse",
"BDSM",
"Kink Negotiation",
"Sex Pollen",
"Tentacles",
"First Time",
"Secret Virgin",
"Heat/Mating Cycles",
"Sex Robot",
"Anthropomorphic",
"Crack Taken Seriously",
"Shapeshifter",
"Sex Shop",
"Need To Be Taught (Ballroom) Dancing",
"Pornstar AU",
"Camgirl/camboy AU",
"Harem AU",
"Fraternity/Sorority",
"Bikers",
"Fantasy",
"Supernatural Creatures",
"Wedding Planner",
"Fake Out Make Out",
"Break Up Make Up",
"Brand/Piercing/Tattoo Kink",
"Drugs/Alcohol",
"Heat/Ice Kink",
"Petplay",
"Sex Toys",
"Crossdressing",
"Body Worship",
"Praise Kink",
"Anonymous Sex",
"D/s",
"Hard Bondage",
"Gags/breathplay/silence",
"Humiliation",
"Service/Obedience Kink",
"Double Penetration",
"Roleplay",
"Voyeurism",
"Exhibitionism",
"Semi-Public Sex",
"Outdoor Sex",
"Phone Sex",
"Car Sex/Road Head",
"Sextape",
"Writing on Body",
"Sexswap",
"Possessive",
"Praise Kink",
"Scent Kink",
"Voice Fetish",
"Mafia/Yakuza/Conmen",
"Mpreg",
"Established Relationship",
"Supervillain",
"Famous Critic",
"Famous Actor",
"Famous Popstar",
"Celebrity",
"Musicians",
"Kidnapped/Hostage",
"Human/Creature Hybrids",
"Office Job",
"Phone Sex Operator",
"Knight/Bodyguard",
"Canon Compliant",
"Fitness (yoga, gym) Instructor",
"Supernatural Creature Hunter",
"Sleepovers",
"Author/Editor",
"Seduction",
"Dance/Ball",
"Accidental Baby Acquisition",
"Art Thief/Heist",
"Fuck or Die",
"Social Media Influencer/Content Creator/Streamer"
);?>