<?php

$prompts = array("Healers/St. Mungos",
"8th year",
"Felix Felicis",
"Amortentia",
"Veritaserum",
"Polyjuice Potion",
"Aurors",
"Auror Partners",
"Veelas",
"Resorting",
"Animagus",
"Mirror of Erised",
"Parseltongue",
"Dark Mark",
"Quidditch",
"Potions Accident",
"First War",
"Second War",
"Slytherin Harry",
"Founders fic",
"Marauders fic",
"Magical Paintings",
"Hogwarts Professor",
"Minister of Magic",
"Epilogue, What Epilogue?",
"Order of the Phoenix",
"Ritual Magic",
"Dumbledore's Army",
"Doesn't Get Their Hogwarts Letter",
"Voldemort finds out about Horcrux hunting",
"The Malfoys join the Order",
"Post-Goblet of Fire AU",
"Post-Order of the Phoenix AU",
"Post-Half Blood Prince AU",
"Epilogue Compliant",
"Unspeakable",
"No Prophecy",
"No Voldemort",
"Cursebreaking",
"Dragon Trainer",
"Travel to America",
"Travel to Australia",
"Triwizard Tournament",
"Dance/Ball",
"Beauxbatons AU",
"Durmstrang AU",
"Life Debt",
"Time Turners",
"Floo/Floo Network",
"Accidental Magic",
"Giant Squid",
"Magical Plants/Herbology",
"Love Potions",
"Magic Hybrid Accident",
"House Unity",
"Room of Requirement",
"Enhanced/Powerful Magic",
"Loss of Magic",
"Potions Master",
"Joke Shops",
"Magical Candy",
"Alchemy",
"Philosopher's Stone",
"Technology in Hogwarts",
"Muggle/Wizard Culture Blend",
"Azkaban",
"Precognition/Future Sight/Seer",
"Hiding Amongst Muggles",
"Magical Bars/Clubs",
"Winter 1994 Yule Ball",
"Gringotts",
"Daily Prophet Ad",
/** not hp specific but popular/common/has roots in canon **/
"Werewolves",
"Vampires",
"Bonded",
"Nonmagic AU",
"Casefic",
"Magical Mistletoe",
"Time Travel/Timeplay",
"Journalism",
"Politicians/Activists",
"Magical Painter",
"Magical Wish Fulfillment/Genies",
"Detention",
"Camping/Hiking",
"PTSD",
"Magical Tattoos",
"Political Corruption",
"Magical Coma",
"Wake Up in Nonmagical Universe",
"Magical Apocalypse",
"Post-Magical Apocalypse",
"Cross Generational",
"Magical Object/Furniture",
"Magical Object Accident",
/** general and suitable **/
"Fake Relationship",
"Accidental Marriage",
"Arranged Marriage",
"Regency/Royalty",
"Canon Divergence",
"Universe Alteration",
"Sharing a Bed",
"Missing Scene/Episode Tag",
"Trapped Together",
"Handcuffed/Physically Bound Together",
"Matchmaking",
"Coffeeshop",
"Bodyswap",
"Daemon AU",
"5+1",
"Holidayfic",
"Amnesia",
"Character Study",
"Presumed Dead",
"Doppelgangers",
"Animal Transformation",
"Pet Trainer/Magical Animal Care",
"Vigilantism",
"Wingfic",
"Role Reversal",
"Bets/Wagers",
"Dating Show",
"Game Show",
"Bachelor Auction",
"Roadtrip",
"Fake Out Make Out",
"Timeloop",
"Enemies with Benefits",
"Friends with Benefits",
"Childhood Friends AU",
"Met Later In Canon AU",
"De-aging Kidfic",
"Kidfic",
"Community Service",
"Femslash/slash AU",
"Store Owner",
"Character Death Fix",
"Bakery/Chef/Restaurant AU",
"Ghosts",
"Fever Dream",
"Afterlife",
"Didn't Know They Were Dating",
"Bodyguard/Knight",
"Epistolary",
"Twin AU",
"Sickfic/illness",
"Identity Porn/Comedy of Errors",
"Kissing Practice",
"Locked in a Room",
"Let Me Be Weak, Let Me Sleep",
"Catboy/Kemonomimi",
"Merpeople/Selkie",
"Neighbors",
"Roommates",
"Party Games (7 Mins in Heaven, Spin The Bottle, Gay Chicken)",
"Stripper",
"Single Parent Kidfic",
"Academic Tutor",
"Etiquette/Skill Mentor",
"Soulmates",
"Soulmarks",
"Marriage of Convenience",
"Forced Obedience/Mind Control",
/**/"Omegaverse",
"Nonmagical Boarding School AU",
"Magical Flower Shops",
"Summer Love",
"Drabble Collection",
"Non-Linear",
"Five Things/Times",
"First Love",
"(Muggle) Bars/Clubs",
"Secret Admirers/Anonymous Notes",
"In Vino Veritas",
"Massages",
"Secret Santa/Anonymous Gift Exchange",
"Selfcest",
/**/"Mpreg",
"Dominance Hierarchy",
"Kink Negotiation",
"Genderfuck/Sexswap",
/**/"BDSM",
"Famous/Celebrity",
"Beachfic",
/**/"Seduction",
"Bribery",
"Human/Creature Hybrids",
"Kidnapped/Hostage",
"Famous Critic",
"Established Relationship",
/**/"Brand/Piercing/Tattoo Kink",
/**/"D/s",
/**/"Anonymous Sex",
/**/"Crossdressing",
/**/"Hard Bondage",
"Breakup Make Up",
/**/"Fuck or Die",
/**/"Sex Pollen",
/**/"Harem",
/**/"Magical Sex Shop",
/**/"Heat/Mating Cycles",
/**/"Secret Virgin",
/**/"First Time",
/**/"Virginfic",
/**/"Tentacles",
"Meet Earlier In Canon",
"Pre-Hogwarts",
"Oh Snap It's You Again (& you got hot)",
"Espionage",
"Competitive Rivals",
"Thief",
"Author",
"Musician",
"Deaging"
    );
$house = array("<span class='slyth'>Slytherin</span>", "<span class='puff'>Hufflepuff</span>", "<span class='gryff'>Gryffindor</span>", "<span class='claw'>Ravenclaw</span>");
$character = array("Harry Potter",
"Ron Weasley",
"Hermione Granger",
"Ginny Weasley",
"Cho Chang",
"Marietta Edgecombe",
"Draco Malfoy",
"Dean Thomas",
"Seamus Finnegan",
"Neville Longbottom",
"Parvati Patil",
"Lavender Brown",
"Luna Lovegood",
"Pansy Parkinson",
"Millicent Bulstrode",
"Tracey Davis",
"Theodore Nott",
"Gregory Goyle",
"Vincent Crabbe",
"Marcus Flint",
"Percy Weasley",
"Oliver Wood",
"Blaise Zabini",
"Fred Weasley",
"George Weasley",
"Bill Weasley",
"Charlie Weasley",
"James Potter",
"Lily Evans-Potter",
"Remus Lupin",
"Sirius Black",
"Severus Snape",
"Peter Pettigrew",
"Tom Riddle Jr.",
"Anthony Goldstein",
"Zacharias Smith",
"Hannah Abbott",
"Susan Bones",
"Justin Finch-Fletchley",
"Ernie Macmillan",
"Terry Boot",
"Michael Corner",
"Padma Patil",
"Su Li",
"Sally-Anne Perks",
"Megan Jones",
"Wayne Hopkins",
"Albus Severus",
"James Sirius",
"Lily Luna",
"Rose Weasley",
"Hugo Weasley",
"Lorcan Scamander",
"Lycan Scamander",
"Teddy Lupin",
"Dominique Weasley",
"Victoire Weasley",
"Albus Dumbledore",
"Gellert Grindelwald",
"Scorpius Malfoy",
"Colin Creevey",
"Dennis Creevey",
"Dudley Dursley",
"Cedric Diggory",
"Hagrid",
"Viktor Krum",
"Fleur Delacour",
"'Tonks' Tonks",
"Barty Crouch Jr.",
"Kingsley Shacklebolt",
"Angelina Johnson",
"Katie Bell",
"Alicia Spinnet",
"Regulus Black",
"Bellatrix Lestrange",
"Tina Goldstein",
"Newt Scamander",
"Queenie Goldstein",
"Credence Barebone",
"Jacob Kowalski",
"Seraphina Picquery",
"Minerva McGonagall",
"Godric Gryffindor",
"Rowena Ravenclaw",
"Helga Hufflepuff",
"Salazar Slytherin",
"Cormac McLaggen",
"Rita Skeeter",
"Narcissa Malfoy/Black",
"Lucius Malfoy",
"Penelope Clearwater",
"Roger Davies",
"Petunia Evans",
"Merope Gaunt",
"Fenrir Greyback",
"Lee Jordan",
"Demelza Robins",
"Astoria Greengrass",
"Daphne Greengrass",
"Andromeda Tonks",
"Romilda Vane",
"Molly Weasley",
"Helena Ravenclaw");
$friends = array("Harry", "Hermione", "Ron", "Draco", "Neville", "Ginny", "Luna", "Pansy", "Parvati", "Lavender", "Dean", "Seamus", "Zacharias", "Ernie", "Millicent", "Vincent", "Gregory", "Theodore", "Blaise", "Justin", "Hannah", "Susan", "Anthony", "Terry", "Michael", "Padma", "Su", "Wayne", "Morag", "Tracey", "Sally-Anne", "Megan", "Daphne", "Mandy");
$multi = array("fake dating", "vampires", "historical", "royalty", "werewolves", "post-magic apocalypse", "magic apocalypse", "daemon", "modern day", "break up then make up", "fake out make out", "omegaverse", "accidental marriage", "arranged marriage", "sharing a bed", "trapped together", "bonded (physical pain)", "bonded (telepath/empath)", "handcuffed/physically bound together", "matchmaking", "bodyswap", "coffeeshop", "espionage", "casefic/mystery", "wingfic", "5+1", "holidayfic", "time travel/timeplay", "amnesia", "presumed dead", "doppelgangers", "twin au", "animal transformation", "role reversal", "bets/wagers", "oh snap it's you again", "marriage of convenience", "bachelor/dating show", "bachelor auction", "roadtrip", "soulmate", "fake dating", "groundhog day/timeloop", "enemies with benefits", "friends with benefits", "competitive rivals", "enemies", "childhood friends", "met later/earlier", "maids", "femslash/slash au", "ghosts", "shopowner", "bakery", "chef/restaurant", "famous critic", "sick/illness", "didn't know they were dating", "identity porn/comedy of errors", "kissing practice", "locked in a room", "let me be weak, let me sleep", "catboy/kemonomimi", "were-creature", "mermaids", "neighbors", "roommates", "magical tattoos", "stripper", "party games (7 mins in heaven, spin the bottle, gay chicken)", "single parent", "established relationship", "getting together", "forced obedience/mind control", "boarding school", "magical florist", "summer love", "first love", "thief", "curseworkers", "magical painter",  "musician", "in vino veritas", "massages", "secret admirer", "anonymous notes", "secret santa/anonymous gift exchange", "bdsm", "mpreg", "harem",  "etiquette/skill mentor", "sex pollen", "virginfic", "first time", "secret virgin", "heat/mating cycles", "magical sex shop", "fuck or die", "pet trainer/magical animal care", "bodyguard/knight", "canon compliant", "post-canon", "pre-canon", "human/creature hybrids", "power imbalance", "dominance hierarchy", "genderfuck/sexswap", "epistolary/chatfic", "beachfic", "muggle bars/clubs", "selfcest", "kidnapping/hostage", "camping/hiking", "Healers/St. Mungos", "8th year", "Felix Felicis", "Amortentia", "Veritaserum", "Polyjuice Potion", "Aurors", "Auror Partners", "Veelas", "Resorting", "Animagus", "Mirror of Erised", "Parseltongue", "Dark Mark", "Quidditch", "Potions Accident", "First War", "Second War", "Slytherin Harry", "Founders fic", "Marauders fic", "Magical Paintings", "Hogwarts Professor", "Minister of Magic", "Epilogue, What Epilogue?", "Order of the Phoenix", "Ritual Magic", "Dumbledore's Army", "Doesn't Get Their Hogwarts Letter", "Voldemort finds out about Horcrux hunting", "The Malfoys join the Order", "Post-Goblet of Fire AU", "Post-Order of the Phoenix AU", "Post-Half Blood Prince AU", "Epilogue Compliant", "Unspeakable", "No Prophecy", "No Voldemort", "Cursebreaking", "Dragon Trainer", "Travel to America", "Travel to Australia", "Triwizard Tournament", "Dance/Ball", "Beauxbatons AU", "Durmstrang AU", "Life Debt", "Time Turners", "Floo", "Accidental Magic", "Giant Squid", "Magical Plants/Herbology", "Love Potions", "Magic Hybrid Accident", "House Unity", "Room of Requirement", "Enhanced/Powerful Magic", "Loss of Magic", "Potions Master", "Joke Shops", "Magical Candy", "Alchemy", "Philosopher's Stone", "Technology in Hogwarts", "Muggle/Wizard Culture Blend", "Azkaban", "Precognition/Future Sight/Seer", "Hiding Amongst Muggles", "Magical Bars/Clubs", "Winter 1994 Yule Ball", "Gringotts", "Daily Prophet Ad", "nonmagic", "magical mistletoe", "journalism", "politicians/activists", "magical wish fulfillment/genies", "detention", "ptsd", "political corruption", "magical coma", "wake up in nonmagical universe", "boarding school",  "cross generational", "Kink Negotiation", "Famous/Celebrity", "Seduction", "bribery", "brand/piercing/tattoo kink", "d/s", "anonymous sex", "crossdressing", "hard bondage", "de-aging", "kidfic", "pre-hogwarts", "tentacles", "Magical Object/Furniture", "Magical Object Accident");
?>