<?php
$kinks = array("fisting",
"branding",
"piercing",
"tattooing",
"bruising or bitemarks",
"aphrodisiacs",
"drugs",
"food",
"temperature play",
"suspension",
"deepthroating",
"spanking/paddling",
"petplay",
"orgasm denial",
"teasing",
"tickling",
"object penetration (toys – worn under clothes)",
"object penetration (toys – not worn)",
"object penetration (objects not designed for sex)",
"bondage (held down)",
"bondage (immobility)",
"bondage (wrist restraints)",
"bondage (full body)/hojojutsu",
"tentacles",
"crossdressing (outerwear)",
"crossdressing (underwear/lingerie)",
"foot fetish",
"hand fetish",
"ear fetish",
"armpit fetish",
"finger fetish",
"knee fetish",
"glory holes",
"bukkake/facials",
"watersports",
"shaving",
"sensory deprivation (sight)",
"sensory deprivation (sound)",
"sensory deprivation (touch)",
"sensation play",
"gags + blindfolds + bondage",
"breathplay",
"gags",
"silence",
"barebacking",
"humiliation (public)",
"humiliation (private)",
"humiliation (verbal)",
"obedience",
"dirty talk",
"candle play",
"gangbang",
"orgy",
"double penetration (one hole)",
"double penetration (two holes)",
"consent play",
"flogging",
"caning",
"knifeplay",
"gunplay",
"roleplay/au (authority figures)",
"roleplay/au (historical)",
"roleplay/au (domestic/tradesmen)",
"roleplay/au (prostitute)",
"roleplay/au (master/slave)",
"roleplay/au (ddlg)",
"roleplay/au",
"virginity/celibacy",
"costumes",
"striptease",
"genital torture",
"electricity",
"enemas",
"fucking machines",
"nippleplay",
"leather/latex",
"locked up",
"voyeurism",
"exhibitionism",
"public sex",
"outdoor sex",
"phonesex",
"rimming",
"felching",
"vehicular",
"road head",
"plushies/furries",
"snowballing",
"cockrings",
"rough sex",
"kama sutra (extreme positions)",
"film/photography",
"begging",
"sleepy/unconscious",
"writing on the body",
"washing/cleaning each other",
"pegging/strap-ons",
"anonymous sex",
"chastity devices",
"mirrors",
"penance/punishment",
"docking",
"sexswap",
"praise kink",
"tentacles",
"knotting",
"size kink",
"heats/mating cycles",
"boot worship",
"omorashi",
"figging",
"virginfic",
"iceplay",
"sadism",
"masochism",
"bdsm",
"d/s",
"cockwarming",
"sounding",
"service kink",
"dacryphilia (crying kink)",
"scent kink",
"voice fetish",
"vore",
"cannibalism",
"69",
"intercrural sex",
"intergluteal sex",
"comeplay",
"collaring",
"lactation",
"impregnation/breeding",
"inflation",
"fingering come back in",
"coming inside",
"dryfucking",
"ankle fetish",
"wrist fetish",
"masseuse",
"edging",
"anal beads",
"fleshlights",
"oviposition",
"creature/alien/monster",
"frottage",
"riding",
"topping from the bottom",
"facefucking",
"body worship",
"sex robot",
"sextape",
"Fuck or die"
);?>