<?php

$main = array("Wei Wuxian", "Lan Wangji", "Jiang Cheng", "Jiang Yanli", "Jiang Fengmian", "Yu Ziyuan", "Lan Xichen", "Lan Qiren", "Lan Sizhui", "Lan Jingyi", "Jin Ling", "Jin Guangyao", "Jin Zixuan", "Jin Guangshan", "Wen Ruohan", "Wen Chao", "Wen Zhuliu", "Wen Ning", "Wen Qing", "Wang Lingjiao", "Ouyang Zizhen", "Mo Xuanyu", "Xiao Xingchen", "Song Lan", "Xue Yang", "Nie Mingjue", "Nie Huaisang", "Luo Qingyang (Mianmian)", "A-Qing", "Qin Su", "Su She");

$all = array("Wei Wuxian", "Lan Wangji", "Jiang Cheng", "Jiang Yanli", "Jiang Fengmian", "Yu Ziyuan", "Lan Xichen", "Lan Qiren", "Lan Sizhui", "Lan Jingyi", "Jin Ling", "Jin Guangyao", "Jin Zixuan", "Jin Guangshan", "Wen Ruohan", "Wen Chao", "Wen Zhuliu", "Wen Ning", "Wen Qing", "Wang Lingjiao", "Ouyang Zizhen", "Mo Xuanyu", "Xiao Xingchen", "Song Lan", "Xue Yang", "Nie Mingjue", "Nie Huaisang", "Luo Qingyang (Mianmian)", "A-Qing", "Qin Su", "Jin Zixun", "Cangse Sanren", "Baoshan Sanren", "Bicao", "Sect Leader Ouyang", "Sect Leader Yao", "Fairy", "Granny Wen", "Uncle Four", "Jin Rusong", "Jin Chan", "Lan Yi", "Little Apple", "Madam Jin", "Meng Shi", "Nie Zonghui", "Sisi", "Wei Changze", "Wen Xu", "Tulu Xuanwu", "Chenqing", "Bichen", "Suibian", "Madam Lan", "Qingheng-jun", "Su She");

/**characters**/

$oldies = array("Cangse Sanren", "Baoshan Sanren", "Lan Qiren", "Lan Yi", "Madam Lan", "Qingheng-jun", "Jiang Fengmian", "Yu Ziyuan", "Wen Ruohan", "Wen Zhuliu", "Jin Guangshan", "Madam Jin", "Wei Changze", "Sect Leader Ouyang", "Sect Leader Yao", "Granny Wen", "Uncle Four", "Meng Shi");

$normies = array("Wei Wuxian", "Lan Wangji", "Jiang Cheng", "Jiang Yanli", "Lan Xichen", "Jin Guangyao", "Jin Zixuan", "Wen Ning", "Wen Qing", "Wang Lingjiao", "Wen Chao", "Wen Xu", "Mo Xuanyu", "Xiao Xingchen", "Song Lan", "Xue Yang", "Nie Mingjue", "Nie Huaisang", "Luo Qingyang (Mianmian)", "Qin Su", "Su She", "Jin Zixun");

$popular = array("Wei Wuxian/Lan Wangji", "Jiang Cheng/Lan Xichen", "Jiang Cheng/Nie Huaisang", "Lan Xichen/Jin Guangyao", "Lan Xichen/Nie Mingjue", "Lan Xichen/Nie Mingjue/Jin Guangyao", "Nie Mingjue/Jin Guangyao", "Jin Zixuan/Jiang Yanli", "Xue Yang/Xiao Xingchen", "Xiao Xingchen/Song Lan", "Xue Yang/Xiao Xingchen/Song Lan", "Jiang Cheng &/ Wei Wuxian", "Lan Jingyi/Lan Sizhui", "Jin Ling/Lan Sizhui", "Jin Ling/Lan Jingyi", "Jin Ling/Lan Jingyi/Lan Sizhui", "Jin Ling/Lan Jingyi/Lan Sizhui/Ouyang Zizhen", "Wen Qing/Jiang Cheng", "Jiang Yanli/Wen Qing", "Wen Qing/Mianmian", "Nie Huaisang/Jin Guangyao", "Wei Wuxian/Lan Wangji","Wei Wuxian/Lan Wangji","Wei Wuxian/Lan Wangji","Wei Wuxian/Lan Wangji","Wei Wuxian/Lan Wangji");

/** prompts **/
$sects = array("<span class='jiang'>Yunmeng Jiang</span>", "<span class='jin'>Lanling Jin</span>", "<span class='lan'>Gusu Lan</span>", "<span class='nie'>Qinghe Nie</span>", "<span class='wen'>Qishan Wen</span>", "Yao", "Ouyang");

$prompts = array(
    /** mdzs specific **/
    "Main Story Retelling",
    "Modern Day Cultivation",
"Dual Cultivation",
"Cursefic",
"Raised By A Different Sect", 
"Accidental Marriage Ritual",
"Golden Core Removal",
"Yiling Wei Sect",
"Character Creates Own Sect",
"Qiongqi Path Divergence",
"Xuanwu Cave Divergence",
"Everyone Lives/Nobody Dies",
"Nobody Lives/Everyone Dies",
"Dragons",
"Bunnies",
"Foxes",
"Succubus",
"Lans & Alcohol",
"Golden Core Transplant",
"Cloud Recesses' 4000+ Rules",
"Cangse Sanren & Wei Changze Live",
"Sunshot Campaign Divergence",
/** not mdzs specific but has roots in canon **/
"Casefic",
"Ghostfic",
"Truth-Telling Curse",
"Sex Curse",
"Bonded (physical distance causing pain)",
"Bonded (telepathy)",
"Bonded (telepathy & physical distance causing pain)",
"Timeloop",
"Amnesia",
"Time Travel/Time Play",
"Magical Wish Fulfillment",
"Magical/Cursed Art",
"Magical/Cursed Environment",
"Magical/Cursed Devices/Tools",
"Magical/Cursed Weapons",
"Temporary Death",
"PTSD",
"Character Death Fix",
"Political Corruption",
"Wake Up In Alternate Timeline",
"Wake Up In Modern Universe",
"Magical Coma",
"Apocalypse",
"Post-Apocalyptic",
"Magical/Cursed Furniture",
"Magical/Cursed Accident",
"Arranged Marriage",
"Sect Defection",
/**general and suitable**/
"Politicans/Activists",
"Journalism",
"Werewolves",
"Vampires",
"Camping/Hiking",
"Tattoos",
"Whump",
"Sickfic/Injuryfic",
"Reincarnation",
"Character Death Fix",
"Sugar Daddy",
"Space AU",
"Proxy Fucking",
"Fake Relationship",
"Royalty",
"Ancient Dynasty AU",
"Sharing a Bed",
"Missing Scene/Episode Tag",
"Trapped Together",
"Handcuffed/Physically Bound Together",
"Matchmaking",
"Coffeeshop",
"Bodyswap",
"Daemon AU",
"5+1",
"Holidayfic",
"Presumed Dead",
"Doppelgangers",
"Animal Transformation",
"Rogue Cultivator",
"Wingfic",
"Role Reversal",
"Bets/Wagers",
"Dating Show",
"Game Show",
"Bachelor Auction",
"Roadtrip",
"Fake Out Make Out",
"Enemies with Benefits",
"Friends with Benefits",
"Childhood Friends AU",
"Met Later In Canon AU",
"Met Earlier In Canon AU",
"De-aging Kidfic",
"Kidfic",
"Community Service",
"Femslash/slash AU",
"Store Owner",
"Bakery/Chef/Restaurant AU",
"Ghosts",
"Fever Dream",
"Afterlife",
"Didn't Know They Were Dating",
"Bodyguard/Knight",
"Epistolary",
"Identity Porn/Comedy of Errors",
"Kissing Practice",
"Locked in a Room",
"Let Me Be Weak, Let Me Sleep",
"Catboy/Kemonomimi",
"Merpeople/Selkie",
"Neighbors",
"Roommates",
"Party Games (7 Mins in Heaven, Spin The Bottle, Gay Chicken)",
"Stripper",
"Single Parent Kidfic",
"Academic Tutor",
"Etiquette/Skill Mentor",
"Soulmates",
"Soulmarks",
"Marriage of Convenience",
"Forced Obedience/Mind Control",
"Sex Pollen",
"Fuck or Die",
"Magical Healing Cock",
"Omegaverse",
"Summer Love",
"Drabble Collection",
"Non-Linear",
"Five Things/Times",
"First Love",
"Bars/Clubs",
"Cultivator Bars/Clubs",
"Secret Admirers/Anonymous Notes",
"In Vino Veritas",
"Massages",
"Secret Santa/Anonymous Gift Exchange",
"Selfcest",
"Mpreg",
"Dominance Hierarchy",
"Kink Negotiation",
"Wake Up With Different Genitals",
"BDSM",
"Famous/Celebrity",
"Beachfic",
"Seduction",
"Bribery",
"Human/Creature Hybrids",
"Kidnapped/Hostage",
"Famous Critic",
"Established Relationship",
"Brand/Piercing/Tattoo Kink",
"D/s",
"Anonymous Sex",
"Crossdressing",
"Hard Bondage",
"Breakup Make Up",
"Concubines",
"Heat/Mating Cycles",
"Secret Virgin",
"First Time",
"Virginfic",
"Tentacles",
"Oh Snap It's You Again (& you got hot)",
"Espionage",
"Competitive Rivals",
"Thief",
"Author/Writer AU",
"Musician",
"High School AU",
"University AU",
"Teacher or Professor AU",
"Post-Canon/Futurefic",
"Pre-Canon",
"Fix-It Fic",
"Spy AU",
"Competitive Sport AU",
"Immortals",
"Break Up Make Up",
"Fandom/Internet Celebrity AU",
"Chinese Folktale AU",
"Stranded on Desert Island",
"Hospitalfic",
"Robots",
"Boarding School AU",
"Curseworkers AU",
"Battle Royale/Hunger Games AU",
"Boss/Assistant AU",
"Bystander POV",
"Sex Slaves",
"Genderfuck/Sexswap",
"Pornstar AU",
"Camgirl/onlyfans AU",
"Hanahaki Disease",
"Anthropomorphic",
"Crack Taken Seriously",
"Babysitter",
"Hitman/Assassin",
"Piano Teacher",
"Dancer/Ballet",
"Orchestral Musician",
"Pop Star",
"Receptionist/Secretary",
"Office",
"Freelance Creative",
"Programmer/hacker",
"Retail",
"Call Service",
"Animal Career",
"Customer Service/Retail",
"Serial Killer",
"Author/Editor",
"Ghostwriter",
"Mechanic",
"Magician",
"Sex Tape",
"Canon Compliant",
"Universe Hopping",
"Precognition/Future Sight",
"Economical Class Difference",
"Mistletoe",
"Were-creatures",
"Discipline Whip",
"Cloud Recesses Guest Lecture",
"Guest Lecture At Other Sect(s)",
"Night Hunts",
"Accidental Rituals",
"Archery Competition",
"Night Hunt Competition",
"Song Composition",
"Lotus Pier Survives AU",
"No Sunshot Campaign AU",
"Zidian Kink",
"Weddings",
"Golden Core Transfer Failure",
"Character Death Switch",
"Burial Mounds",
"Different Inventor of Demonic Cultivation",
"Brought Back As A Fierce Corpse",
"Crossover Fusion",
"Family Loyalty",
"Craigslist Ad",
"Xianxia Craigslist Ad",
"Social Media Influencer/Content Creator/Streamer"
);

$multi = array("Main Story Retelling",
    "Foxes",
"Cursed Environment/Artifact",
"Bakery/Chef/Restaurant AU",
"Roommates",
"Fuck or Die",
"Temporary Death",
"Bets/Wagers",
"Bodyswap",
"Competitive Rivals",
"Anonymous Sex",
"Daemon AU",
"Afterlife",
"Identity Porn",
"Yiling Wei Sect",
"Timeloop",
"Fix-It",
"Space AU",
"Character Death Fix",
"Selfcest",
"Politicans/Activists",
"Massages",
"Bodyguard/Knight",
"Competitive Sport AU",
"D/s",
"Wake Up In Modern Universe",
"Hanahaki Disease",
"Neighbors",
"Oh Snap It's You Again",
"Orchestral Musician",
"First Love",
"Precognition",
"Canon Compliant",
"Raised By A Different Sect", 
"Golden Core Removal",
"Physically Bound Together",
"Casefic",
"Everyone Lives",
"Accidental Marriage Ritual",
"Rogue Cultivator",
"Dragons",
"Fever Dream",
"Party Games (7 Mins in Heaven, Spin The Bottle, Gay Chicken)",
"Espionage",
"Cangse Sanren & Wei Changze Live",
"Established Relationship",
"Soulmarks",
"Office",
"Golden Core Transplant",
"Ghostfic",
"Etiquette/Skill Mentor",
"bonded (physical pain)", "bonded (telepath/empath)",
"Animal Career",
"Secret Virgin",
"Bystander POV",
"Dominance Hierarchy",
"Breakup Make Up",
"Boss/Assistant AU",
"Magical Coma",
"Succubus",
"Post-Canon",
"Political Corruption",
"Robots",
"Holidayfic",
"Sex Curse",
"Doppelgangers",
"Whump",
"Concubines",
"Dancer",
"Sect Defection",
"Summer Love",
"Role Reversal",
"Coffeeshop",
"Apocalypse",
"Post-Apocalyptic",
"Immortals",
"Roadtrip",
"Camping/Hiking",
"Battle Royale/Hunger Games AU",
"De-aging Kidfic",
"Hacker",
"Brand/Piercing/Tattoo Kink",
"Soulmates",
"Mpreg",
"Retail",
"Locked in a Room",
"Kissing Practice",
"University AU",
"Catboy",
"Tattoos",
"5+1",
"Missing Scene/Episode Tag",
"Wake Up In Alternate Timeline",
"Call Service",
"Store Owner",
"Lans & Alcohol",
"Forced Obedience/Mind Control",
"Cloud Recesses' 4000+ Rules",
"Animal Transformation",
"Tentacles",
"Heat/Mating Cycles",
"Arranged Marriage",
"Virginfic",
"Vampires",
"Porn Stars",
"Camgirl/onlyfans",
"Proxy Fucking",
"Pre-Canon",
"Wake Up With Different Genitals",
"Kidfic",
"Piano Teacher",
"Marriage of Convenience",
"Enemies with Benefits",
"Sharing a Bed",
"PTSD",
"Sugar Daddy",
"Famous Critic",
"Childhood Friends AU",
"Bars/Clubs",
"Royalty",
"High School AU",
"Crossdressing",
"Epistolary",
"Time Travel",
"Amnesia",
"Thief",
"Dual Cultivation",
"Reincarnation",
"Rule 63",
"Matchmaking",
"Bunnies",
"Friends with Benefits",
"Customer Service",
"Sex Tape",
"First Time",
"Seduction",
"BDSM",
"Bribery",
"Cursefic",
"Freelance Creative",
"Qiongqi Path Divergence",
"Kink Negotiation",
"Sex Pollen",
"Fake Relationship",
"Sickfic/Injuryfic",
"Character Death Fix",
"Truth-Telling Curse",
"Anonymous Notes",
"Kidnapped/Hostage",
"Met Later In Canon AU",
"Five Things/Times",
"Academic Tutor",
"Spy AU",
"Nobody Lives",
"Beachfic",
"Babysitter",
"Break Up Make Up",
"Didn't Know They Were Dating",
"Magical Wish Fulfillment",
"Merpeople",
"Famous/Celebrity",
"Sunshot Campaign Divergence",
"Ghosts",
"Werewolves",
"Non-Linear",
"Single Parent Kidfic",
"Fake Out Make Out",
"Author/Writer AU",
"Drabble Collection",
"Omegaverse",
"Presumed Dead",
"Magical Healing Cock",
"Character Creates Own Sect",
"Xuanwu Cave Divergence",
"Universe Hopping",
"Modern Day Cultivation",
"Trapped Together",
"Wingfic",
"Met Earlier In Canon AU",
"Hitman/Assassin",
"Fandom/Internet Celebrity AU",
"Were-creatures",
"Discipline Whip",
"Cloud Recesses Guest Lecture",
"Guest Lecture At Other Sect(s)",
"Night Hunts",
"Accidental Rituals",
"Archery Competition",
"Night Hunt Competition",
"Song Composition",
"Lotus Pier Survives AU",
"No Sunshot Campaign AU",
"Zidian Kink",
"Weddings",
"Golden Core Transfer Failure",
"Character Death Switch",
"Burial Mounds",
"Different Inventor of Demonic Cultivation",
"Brought Back As A Fierce Corpse",
"Crossover Fusion",
"Family Loyalty",
"Craigslist Ad",
"Xianxia Craigslist Ad",
"Economical Class Difference",
"Social Media Influencer/Content Creator/Streamer"
);
?>