<?php include('sfw.php') ?>

<?php
$nsfw = $sfw;
array_push($nsfw,/**risky overlap **/"Omegaverse",
/**risky overlap**/"BDSM",
/**/"Kink Negotiation",
/**/"Sex Pollen",
/**/"Tentacles",
/**/"Virginfic",
/**/"First Time",
/**/"Secret Virgin",
/**/"Heat/Mating Cycles",
/**/"Sex Robot",
/**/"Sex Shop",
/**risky overlap **/"Pornstar AU",
/**risky overlap **/"Camgirl/camboy AU",
/**risky overlap **/ "Harem AU",
/**risky overlap**/ "Sex Slaves",
/**/"Wedding Planner",
/**/"Fake Out Make Out",
/**/"Break Up Make Up",
/**/"Sextape",
/********* risky overlap but v popular *********/ "Mafia/Yakuza/Conmen",
/**/"Writing on Body",
/**/"Possessive",
/**/"Praise Kink",
/**/"Scent Kink",
/**/"Voice Fetish",
/**/"Heat/Ice Kink",
/**/"Petplay",
/**/"Sex Toys",
/**/"Crossdressing",
/**/"Body Worship",
/**/"Praise Kink",
/**/"Anonymous Sex",
/**/"D/s",
/**/"Hard Bondage",
/**/"Gags/breathplay/silence",
/**/"Humiliation",
/**/"Service/Obedience Kink",
/**/"Double Penetration",
/**/"Roleplay",
/**/"Voyeurism",
/**/"Exhibitionism",
/**/"Semi-Public Sex",
/**/"Outdoor Sex",
/**/"Phone Sex",
/**/"Car Sex/Road Head",
/**/"Brand/Piercing/Tattoo Kink",
/**/"Phone Sex Operator",
/**/"Seduction",
"Fuck or Die")
?>
