<?php
$sfw = array("Fake Relationship",
"Dance/Ball",
"Accidental Marriage",
"Arranged Marriage",
"Modern Royalty AU",
"Regency AU",
"High School AU",
"University AU",
"Teacher or Professor AU",
"Vampires",
"Werewolves",
"Apocalypse",
"Canon Divergence",
"Post-Canon/Futurefic",
"Pre-Canon",
"Sharing A Bed",
"Trapped Together",
"Bonded (physical pain)",
"Bonded (telepath/empath)",
"Handcuffed/Physically Bound Together",
"Matchmaking",
"Crossover Fusion",
"Fix-It Fic",
"Bodyswap",
"Coffee Shop AU",
"Spy AU",
"Criminal Syndicate AU",
"Casefic/Mystery",
"Economical Class Difference AU",
"Hitman/Assassin AU",
"Hurt/Comfort",
"Angst",
"Flangst",
"Wingfic",
"HDM Daemon AU",
"5+1",
"Holidayfic",
"Reincarnation AU",
"Time Travel",
"Character Study",
"Amnesia",
"Presumed Dead",
"Doppelgangers",
"Animal Transformation",
"Missing Scene/Episode Tag",
"Role Reversal",
"Mirror Universe",
"Bets/Wagers",
"Oh Snap It's You Again",
"Oh Snap It's You Again (& you got hot)",
"Utopia/Dystopia AU",
"Competitive Sport AU",
"The Bachelor/Dating Show",
"Game Show",
"Bachelor Auction",
"Immortals",
"Roadtrip",
"Soulmate Identifying Marks",
"Fake Out Make Out",
"Break Up Make Up",
"Groundhog Day/Timeloop",
"Enemies with Benefits",
"Friends with Benefits",
"Childhood Friends (AU)",
"Met Later In Canon AU",
"De-aging Kidfic",
"Hired Maid",
"Femslash/slash AU",
"Independent Business Owner",
"Character Death Fix",
"Bakery/Chef/Restaurant AU",
"Ghostfic",
"Afterlife",
"Fever Dream",
"Angel/Human",
"Angel/Demon",
"Demon/Human",
"Superpowers AU",
"Superhero AU",
"Didn't Know They Were Dating",
"Space AU",
"Pirate AU",
"Steampunk AU",
"Epistolary",
"Twin AU",
"Fandom/Internet Celebrity AU",
"Recursive Fic",
"Identity Porn/Comedy of Errors",
"Kissing Practice",
"Locked in a Room",
"Let Me Be Weak, Let Me Sleep",
"Catboy/Kemonomimi",
"Merpeople/Selkie AU",
"Mythology AU",
"Neighbors AU",
"Roommates AU",
"Magical Tattoos",
"Seven Minutes In Heaven",
"Spin the Bottle",
"Single Parent Kidfic",
"Kidfic",
"Stranded on Desert Island",
"Kids AU",
"Soulmate AU",
"Marriage of Convenience",
"Hospitalfic",
"Forced Obedience/Mind Control",
"Robots",
"Universe Alteration",
"Denialfic",
"Fairytale AU",
"Boarding School AU",
"Flower Shop AU",
"Summer Love",
"Drabble Collection",
"Non-Linear",
"Five Things/Times",
"First Love",
"Gay Chicken",
"Sickfic",
"Bars/Clubs",
"Thief AU",
"[Public Figure or Boss]/Assistant AU",
"Bystander POV",
"Secret Admirers/Anonymous Notes",
"In Vino Veritas",
"Massages",
"Secret Santa",
"Magic/Nonmagic AU",
"Competitive Rivals",
"Beachfic",
"Language Barrier",
"Cultural Barrier",
"Anthropomorphic",
"Crack Taken Seriously",
"Shapeshifter",
"Need To Be Taught (Ballroom) Dancing",
"Craigslist Ad",
"Human/Creature Hybrids",
"Wedding Planner",
"Established Relationship",
"Supervillain",
"Famous Critic",
"Famous Actor",
"Famous Popstar",
"Celebrity",
"Musician(s)",
"Kidnapped/Hostage",
"Office Job",
"Knight/Bodyguard",
"Canon Compliant",
"Fitness (yoga, gym) Instructor",
"Supernatural Creature Hunter",
"Author/Editor",
"Universe Hopping",
"Camping/Hiking",
"Bribery",
"Magical Wish Fulfillment/Genies",
"Academic Tutor",
"Etiquette/Skill Mentor",
"Precognition/Future Sight",
"Mistletoe",
"Summer Camp",
"Art Thief/Heist",
"Social Media Influencer/Content Creator/Streamer"
);
?>