<?php
$situation = array("fake dating",
"dopplegangers/twins",
"dance/ball",
"accidental marriage",
"arranged marriage",
"economical class difference",
"sharing a bed",
"trapped together",
"bonded (physical pain)",
"bonded (telepath/empath)",
"handcuffed/physically bond together",
"matchmaking",
"fix-it",
"bodyswap",
"casefic/mystery",
"hurt/comfort",
"flangst",
"angst",
"wingfic",
"presumed dead",
"time travel",
"amnesia",
"epistolary",
"5 + 1",
"holidayfic",
"animal transformation",
"secret virgin",
"heat/mating cycles",
"need to be taught (ballroom) dancing",
"shapeshifter",
"crack taken seriously",
"secret virgin",
"first time",
"virginfic",
"tentacles",
"sex pollen",
"kink negotiation",
"bdsm",
"cultural barrier",
"language barrier",
"beachfic",
"competitive rivals",
"secret santa",
"massage",
"in vino veritas",
"secret admirers/anonymous notes",
"bystander pov",
"bars/clubs",
"illness/sickfic",
"gay chicken",
"first love",
"five things/times",
"non-linear",
"drabble collection",
"summer love",
"forced obedience/mind control",
"hospitalfic",
"marriage of convenience",
"soulmates",
"stranded on desert island",
"single parent kidfic",
"spin the bottle",
"seven minutes in heaven",
"let me be weak, let me sleep",
"kissing practice",
"identity porn/comedy of errors",
"fandom/internet celebrities",
"twin au",
"didn't know they were dating",
"fever dream",
"deaging",
"power imbalance",
"friends with benefits",
"enemies with benefits",
"groundhog day/timeloop",
"roadtrip",
"bachelor auction",
"game show",
"the bachelor/dating show",
"oh snap it's you again",
"bets/wagers",
"selfcest",
"amnesiafic",
"character study",
"time travel",
"mafia/yakuza",
"celebrity",
"mpreg",
"pirates",
"academic tutor",
"rivals au",
"enemies au",
"sex slaves",
"genderfuck/sexswap",
"disability",
"possessive",
"craigslist ad",
"fake out make out",
"break up make up",
"sextape",
"established relationship",
"kidnapped/hostage",
"Camping/Hiking",
"Bribery",
"Magical Wish Fulfillment/Genies",
"Precognition/Future Sight",
"Mistletoe",
"PTSD/Trauma",
"Summer Camp",
"Accidental Baby Acquisition",
"Art Thief/Heist",
"fuck or die"
);?>