<?php
$verse = array("canon",
"post-canon/futurefic",
"post-apocalyptic",
"pre-canon",
"fantasy",
"mechanical scifi",
"zombie apocalypse",
"environmental apocalypse",
"robot apocalypse",
"modern au",
"historical au",
"regency au",
"vampires",
"werewolves",
"space",
"pirates",
"canon divergence",
"crossover fusion",
"zombies",
"reincarnation",
"mirrorverse",
"role reversal",
"fantasy",
"supernatural",
"anthropomorphic",
"omegaverse",
"magic au",
"nonmagic au",
"superpowers au",
"mythology au",
"fairytale au",
"human/creature hybrids",
"denialfic",
"universe alteration",
"robots",
"soulmates",
"magical tattoos",
"roommates",
"neighbors",
"merpeople/selkies",
"catboy/kemonomimi",
"recursive fic",
"fandom au",
"twin au",
"steampunk",
"superhero",
"supervillain",
"angels",
"demons",
"afterlife",
"ghosts",
"character death fix",
"femslash/slash au",
"age difference au",
"met later in canon",
"childhood friends au",
"soulmate identifying marks",
"immortals/gods",
"doppelgangers",
"daemon au",
"reincarnation",
"mafia/yakuza",
"high school",
"college/university",
"sex slaves",
"dominance hierarchy",
"genderfuck/sexswap",
"hunger games/battle royale au",
"dystopia/utopia",
"Summer Camp"
);
?>